// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// DomainTooShortError - The domain name (excluding the TLD) is too short.
type DomainTooShortError struct {
	Status   float64                       `json:"status"`
	Code     components.DomainTooShortCode `json:"code"`
	Message  string                        `json:"message"`
	HTTPMeta components.HTTPMetadata       `json:"-"`
}

var _ error = &DomainTooShortError{}

func (e *DomainTooShortError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
