// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type GetBulkAvailabilityInternalServerErrorType string

const (
	GetBulkAvailabilityInternalServerErrorTypeUnauthorizedError          GetBulkAvailabilityInternalServerErrorType = "Unauthorized_error"
	GetBulkAvailabilityInternalServerErrorTypeNotAuthorizedForScopeError GetBulkAvailabilityInternalServerErrorType = "NotAuthorizedForScope_error"
	GetBulkAvailabilityInternalServerErrorTypeInternalServerErrorError   GetBulkAvailabilityInternalServerErrorType = "InternalServerError_error"
)

// GetBulkAvailabilityInternalServerError - Unauthorized
type GetBulkAvailabilityInternalServerError struct {
	UnauthorizedError          *UnauthorizedError          `queryParam:"inline"`
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	InternalServerErrorError   *InternalServerErrorError   `queryParam:"inline"`

	Type GetBulkAvailabilityInternalServerErrorType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetBulkAvailabilityInternalServerError{}

func CreateGetBulkAvailabilityInternalServerErrorUnauthorizedError(unauthorizedError UnauthorizedError) GetBulkAvailabilityInternalServerError {
	typ := GetBulkAvailabilityInternalServerErrorTypeUnauthorizedError

	return GetBulkAvailabilityInternalServerError{
		UnauthorizedError: &unauthorizedError,
		Type:              typ,
	}
}

func CreateGetBulkAvailabilityInternalServerErrorNotAuthorizedForScopeError(notAuthorizedForScopeError NotAuthorizedForScopeError) GetBulkAvailabilityInternalServerError {
	typ := GetBulkAvailabilityInternalServerErrorTypeNotAuthorizedForScopeError

	return GetBulkAvailabilityInternalServerError{
		NotAuthorizedForScopeError: &notAuthorizedForScopeError,
		Type:                       typ,
	}
}

func CreateGetBulkAvailabilityInternalServerErrorInternalServerErrorError(internalServerErrorError InternalServerErrorError) GetBulkAvailabilityInternalServerError {
	typ := GetBulkAvailabilityInternalServerErrorTypeInternalServerErrorError

	return GetBulkAvailabilityInternalServerError{
		InternalServerErrorError: &internalServerErrorError,
		Type:                     typ,
	}
}

func (u *GetBulkAvailabilityInternalServerError) UnmarshalJSON(data []byte) error {

	var unauthorizedError UnauthorizedError = UnauthorizedError{}
	if err := utils.UnmarshalJSON(data, &unauthorizedError, "", true, nil); err == nil {
		u.UnauthorizedError = &unauthorizedError
		u.Type = GetBulkAvailabilityInternalServerErrorTypeUnauthorizedError
		return nil
	}

	var notAuthorizedForScopeError NotAuthorizedForScopeError = NotAuthorizedForScopeError{}
	if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err == nil {
		u.NotAuthorizedForScopeError = &notAuthorizedForScopeError
		u.Type = GetBulkAvailabilityInternalServerErrorTypeNotAuthorizedForScopeError
		return nil
	}

	var internalServerErrorError InternalServerErrorError = InternalServerErrorError{}
	if err := utils.UnmarshalJSON(data, &internalServerErrorError, "", true, nil); err == nil {
		u.InternalServerErrorError = &internalServerErrorError
		u.Type = GetBulkAvailabilityInternalServerErrorTypeInternalServerErrorError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetBulkAvailabilityInternalServerError", string(data))
}

func (u GetBulkAvailabilityInternalServerError) MarshalJSON() ([]byte, error) {
	if u.UnauthorizedError != nil {
		return utils.MarshalJSON(u.UnauthorizedError, "", true)
	}

	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.InternalServerErrorError != nil {
		return utils.MarshalJSON(u.InternalServerErrorError, "", true)
	}

	return nil, errors.New("could not marshal union type GetBulkAvailabilityInternalServerError: all fields are null")
}

func (u GetBulkAvailabilityInternalServerError) Error() string {
	switch u.Type {
	case GetBulkAvailabilityInternalServerErrorTypeUnauthorizedError:
		data, _ := json.Marshal(u.UnauthorizedError)
		return string(data)
	case GetBulkAvailabilityInternalServerErrorTypeNotAuthorizedForScopeError:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case GetBulkAvailabilityInternalServerErrorTypeInternalServerErrorError:
		data, _ := json.Marshal(u.InternalServerErrorError)
		return string(data)
	default:
		return "unknown error"
	}
}
