// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type GetDomainPriceInternalServerErrorType string

const (
	GetDomainPriceInternalServerErrorTypeUnauthorizedError          GetDomainPriceInternalServerErrorType = "Unauthorized_error"
	GetDomainPriceInternalServerErrorTypeNotAuthorizedForScopeError GetDomainPriceInternalServerErrorType = "NotAuthorizedForScope_error"
	GetDomainPriceInternalServerErrorTypeInternalServerErrorError   GetDomainPriceInternalServerErrorType = "InternalServerError_error"
)

// GetDomainPriceInternalServerError - Unauthorized
type GetDomainPriceInternalServerError struct {
	UnauthorizedError          *UnauthorizedError          `queryParam:"inline"`
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	InternalServerErrorError   *InternalServerErrorError   `queryParam:"inline"`

	Type GetDomainPriceInternalServerErrorType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetDomainPriceInternalServerError{}

func CreateGetDomainPriceInternalServerErrorUnauthorizedError(unauthorizedError UnauthorizedError) GetDomainPriceInternalServerError {
	typ := GetDomainPriceInternalServerErrorTypeUnauthorizedError

	return GetDomainPriceInternalServerError{
		UnauthorizedError: &unauthorizedError,
		Type:              typ,
	}
}

func CreateGetDomainPriceInternalServerErrorNotAuthorizedForScopeError(notAuthorizedForScopeError NotAuthorizedForScopeError) GetDomainPriceInternalServerError {
	typ := GetDomainPriceInternalServerErrorTypeNotAuthorizedForScopeError

	return GetDomainPriceInternalServerError{
		NotAuthorizedForScopeError: &notAuthorizedForScopeError,
		Type:                       typ,
	}
}

func CreateGetDomainPriceInternalServerErrorInternalServerErrorError(internalServerErrorError InternalServerErrorError) GetDomainPriceInternalServerError {
	typ := GetDomainPriceInternalServerErrorTypeInternalServerErrorError

	return GetDomainPriceInternalServerError{
		InternalServerErrorError: &internalServerErrorError,
		Type:                     typ,
	}
}

func (u *GetDomainPriceInternalServerError) UnmarshalJSON(data []byte) error {

	var unauthorizedError UnauthorizedError = UnauthorizedError{}
	if err := utils.UnmarshalJSON(data, &unauthorizedError, "", true, nil); err == nil {
		u.UnauthorizedError = &unauthorizedError
		u.Type = GetDomainPriceInternalServerErrorTypeUnauthorizedError
		return nil
	}

	var notAuthorizedForScopeError NotAuthorizedForScopeError = NotAuthorizedForScopeError{}
	if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err == nil {
		u.NotAuthorizedForScopeError = &notAuthorizedForScopeError
		u.Type = GetDomainPriceInternalServerErrorTypeNotAuthorizedForScopeError
		return nil
	}

	var internalServerErrorError InternalServerErrorError = InternalServerErrorError{}
	if err := utils.UnmarshalJSON(data, &internalServerErrorError, "", true, nil); err == nil {
		u.InternalServerErrorError = &internalServerErrorError
		u.Type = GetDomainPriceInternalServerErrorTypeInternalServerErrorError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetDomainPriceInternalServerError", string(data))
}

func (u GetDomainPriceInternalServerError) MarshalJSON() ([]byte, error) {
	if u.UnauthorizedError != nil {
		return utils.MarshalJSON(u.UnauthorizedError, "", true)
	}

	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.InternalServerErrorError != nil {
		return utils.MarshalJSON(u.InternalServerErrorError, "", true)
	}

	return nil, errors.New("could not marshal union type GetDomainPriceInternalServerError: all fields are null")
}

func (u GetDomainPriceInternalServerError) Error() string {
	switch u.Type {
	case GetDomainPriceInternalServerErrorTypeUnauthorizedError:
		data, _ := json.Marshal(u.UnauthorizedError)
		return string(data)
	case GetDomainPriceInternalServerErrorTypeNotAuthorizedForScopeError:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case GetDomainPriceInternalServerErrorTypeInternalServerErrorError:
		data, _ := json.Marshal(u.InternalServerErrorError)
		return string(data)
	default:
		return "unknown error"
	}
}
