// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type GetTldPriceInternalServerErrorType string

const (
	GetTldPriceInternalServerErrorTypeUnauthorizedError          GetTldPriceInternalServerErrorType = "Unauthorized_error"
	GetTldPriceInternalServerErrorTypeNotAuthorizedForScopeError GetTldPriceInternalServerErrorType = "NotAuthorizedForScope_error"
	GetTldPriceInternalServerErrorTypeInternalServerErrorError   GetTldPriceInternalServerErrorType = "InternalServerError_error"
)

// GetTldPriceInternalServerError - Unauthorized
type GetTldPriceInternalServerError struct {
	UnauthorizedError          *UnauthorizedError          `queryParam:"inline"`
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	InternalServerErrorError   *InternalServerErrorError   `queryParam:"inline"`

	Type GetTldPriceInternalServerErrorType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetTldPriceInternalServerError{}

func CreateGetTldPriceInternalServerErrorUnauthorizedError(unauthorizedError UnauthorizedError) GetTldPriceInternalServerError {
	typ := GetTldPriceInternalServerErrorTypeUnauthorizedError

	return GetTldPriceInternalServerError{
		UnauthorizedError: &unauthorizedError,
		Type:              typ,
	}
}

func CreateGetTldPriceInternalServerErrorNotAuthorizedForScopeError(notAuthorizedForScopeError NotAuthorizedForScopeError) GetTldPriceInternalServerError {
	typ := GetTldPriceInternalServerErrorTypeNotAuthorizedForScopeError

	return GetTldPriceInternalServerError{
		NotAuthorizedForScopeError: &notAuthorizedForScopeError,
		Type:                       typ,
	}
}

func CreateGetTldPriceInternalServerErrorInternalServerErrorError(internalServerErrorError InternalServerErrorError) GetTldPriceInternalServerError {
	typ := GetTldPriceInternalServerErrorTypeInternalServerErrorError

	return GetTldPriceInternalServerError{
		InternalServerErrorError: &internalServerErrorError,
		Type:                     typ,
	}
}

func (u *GetTldPriceInternalServerError) UnmarshalJSON(data []byte) error {

	var unauthorizedError UnauthorizedError = UnauthorizedError{}
	if err := utils.UnmarshalJSON(data, &unauthorizedError, "", true, nil); err == nil {
		u.UnauthorizedError = &unauthorizedError
		u.Type = GetTldPriceInternalServerErrorTypeUnauthorizedError
		return nil
	}

	var notAuthorizedForScopeError NotAuthorizedForScopeError = NotAuthorizedForScopeError{}
	if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err == nil {
		u.NotAuthorizedForScopeError = &notAuthorizedForScopeError
		u.Type = GetTldPriceInternalServerErrorTypeNotAuthorizedForScopeError
		return nil
	}

	var internalServerErrorError InternalServerErrorError = InternalServerErrorError{}
	if err := utils.UnmarshalJSON(data, &internalServerErrorError, "", true, nil); err == nil {
		u.InternalServerErrorError = &internalServerErrorError
		u.Type = GetTldPriceInternalServerErrorTypeInternalServerErrorError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetTldPriceInternalServerError", string(data))
}

func (u GetTldPriceInternalServerError) MarshalJSON() ([]byte, error) {
	if u.UnauthorizedError != nil {
		return utils.MarshalJSON(u.UnauthorizedError, "", true)
	}

	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.InternalServerErrorError != nil {
		return utils.MarshalJSON(u.InternalServerErrorError, "", true)
	}

	return nil, errors.New("could not marshal union type GetTldPriceInternalServerError: all fields are null")
}

func (u GetTldPriceInternalServerError) Error() string {
	switch u.Type {
	case GetTldPriceInternalServerErrorTypeUnauthorizedError:
		data, _ := json.Marshal(u.UnauthorizedError)
		return string(data)
	case GetTldPriceInternalServerErrorTypeNotAuthorizedForScopeError:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case GetTldPriceInternalServerErrorTypeInternalServerErrorError:
		data, _ := json.Marshal(u.InternalServerErrorError)
		return string(data)
	default:
		return "unknown error"
	}
}
