/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { billingListBillingCharges } from "../../funcs/billingListBillingCharges.js";
import { ListBillingChargesRequest$inboundSchema } from "../../models/listbillingchargesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListBillingChargesRequest$inboundSchema,
};

export const tool$billingListBillingCharges: ToolDefinition<typeof args> = {
  name: "billing-list-billing-charges",
  description: `List FOCUS billing charges

Returns the billing charge data in FOCUS v1.3 JSONL format for a specified Vercel team, within a date range specified by \`from\` and \`to\` query parameters. Supports 1-day granularity with a maximum date range of 1 year. The response is streamed as newline-delimited JSON (JSONL) and can be optionally compressed with gzip if the \`Accept-Encoding: gzip\` header is provided. This is only available for Owner, Member, Developer, Security, Billing, and Enterprise Viewer roles for the supplied team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await billingListBillingCharges(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
