/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainsRegistrarGetSupportedTlds } from "../../funcs/domainsRegistrarGetSupportedTlds.js";
import { GetSupportedTldsRequest$inboundSchema } from "../../models/getsupportedtldsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSupportedTldsRequest$inboundSchema,
};

export const tool$domainsRegistrarGetSupportedTlds: ToolDefinition<
  typeof args
> = {
  name: "domains-registrar-get-supported-tlds",
  description: `Get supported TLDs

Get a list of TLDs supported by Vercel`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await domainsRegistrarGetSupportedTlds(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
