/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featureFlagsUpdateFlagSegment } from "../../funcs/featureFlagsUpdateFlagSegment.js";
import { UpdateFlagSegmentRequest$inboundSchema } from "../../models/updateflagsegmentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateFlagSegmentRequest$inboundSchema,
};

export const tool$featureFlagsUpdateFlagSegment: ToolDefinition<typeof args> = {
  name: "feature-flags-update-flag-segment",
  description: `Update a segment

Update an existing feature flag segment.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await featureFlagsUpdateFlagSegment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
