/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featureFlagsUpdateFlag } from "../../funcs/featureFlagsUpdateFlag.js";
import { UpdateFlagRequest$inboundSchema } from "../../models/updateflagop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateFlagRequest$inboundSchema,
};

export const tool$featureFlagsUpdateFlag: ToolDefinition<typeof args> = {
  name: "feature-flags-update-flag",
  description: `Update a flag

Update an existing feature flag. This endpoint supports partial updates, allowing you to modify specific properties like variants, environments, or state without providing the full flag configuration.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await featureFlagsUpdateFlag(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
