/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { marketplaceUpdateInstallation } from "../../funcs/marketplaceUpdateInstallation.js";
import { UpdateInstallationRequest$inboundSchema } from "../../models/updateinstallationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateInstallationRequest$inboundSchema,
};

export const tool$marketplaceUpdateInstallation: ToolDefinition<typeof args> = {
  name: "marketplace-update-installation",
  description: `Update Installation

This endpoint updates an integration installation.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await marketplaceUpdateInstallation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
