/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsUploadProjectAvatar } from "../../funcs/projectsUploadProjectAvatar.js";
import { UploadProjectAvatarRequest$inboundSchema } from "../../models/uploadprojectavatarmanagedrules.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UploadProjectAvatarRequest$inboundSchema,
};

export const tool$projectsUploadProjectAvatar: ToolDefinition<typeof args> = {
  name: "projects-upload-project-avatar",
  description: `Upload a project avatar

Upload an image as the avatar of the project identified by \`idOrName\`. The request body is the raw bytes of a JPG, PNG, or SVG image; the \`Content-Type\` header must declare which. SVG payloads are sanitized and optimized server-side before storage. The final SHA-1 of the stored bytes becomes the project's \`avatar\` value.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await projectsUploadProjectAvatar(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
