/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teamsUpdateMicrofrontendsGroup } from "../../funcs/teamsUpdateMicrofrontendsGroup.js";
import { UpdateMicrofrontendsGroupRequest$inboundSchema } from "../../models/updatemicrofrontendsgroupop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateMicrofrontendsGroupRequest$inboundSchema,
};

export const tool$teamsUpdateMicrofrontendsGroup: ToolDefinition<typeof args> =
  {
    name: "teams-update-microfrontends-group",
    description: `Update a microfrontends group

Updates the name (and slug) of a microfrontends group.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await teamsUpdateMicrofrontendsGroup(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
