/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { VercelCore } from "../core.js";
import { encodeJSON } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { pathToFunc } from "../lib/url.js";
import {
  CreateApiKeysRequestBody,
  CreateApiKeysRequestBody$outboundSchema,
  CreateApiKeysResponse403ResponseBody,
  CreateApiKeysResponse403ResponseBody$inboundSchema,
  CreateApiKeysResponse429ResponseBody,
  CreateApiKeysResponse429ResponseBody$inboundSchema,
  CreateApiKeysResponse500ResponseBody,
  CreateApiKeysResponse500ResponseBody$inboundSchema,
  CreateApiKeysResponseBody,
  CreateApiKeysResponseBody$inboundSchema,
  CreateApiKeysResponseResponseBody,
  CreateApiKeysResponseResponseBody$inboundSchema,
} from "../models/createapikeysop.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/httpclienterrors.js";
import { ResponseValidationError } from "../models/responsevalidationerror.js";
import { SDKValidationError } from "../models/sdkvalidationerror.js";
import { VercelError } from "../models/vercelerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

export function createApiKeys(
  client: VercelCore,
  request?: CreateApiKeysRequestBody | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    CreateApiKeysResponseBody,
    | CreateApiKeysResponseResponseBody
    | CreateApiKeysResponse403ResponseBody
    | CreateApiKeysResponse429ResponseBody
    | CreateApiKeysResponse500ResponseBody
    | VercelError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: VercelCore,
  request?: CreateApiKeysRequestBody | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      CreateApiKeysResponseBody,
      | CreateApiKeysResponseResponseBody
      | CreateApiKeysResponse403ResponseBody
      | CreateApiKeysResponse429ResponseBody
      | CreateApiKeysResponse500ResponseBody
      | VercelError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => CreateApiKeysRequestBody$outboundSchema.optional().parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = payload === undefined
    ? null
    : encodeJSON("body", payload, { explode: true });

  const path = pathToFunc("/api-keys")();

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "createApiKeys",
    oAuth2Scopes: null,

    resolvedSecurity: null,

    securitySource: null,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    CreateApiKeysResponseBody,
    | CreateApiKeysResponseResponseBody
    | CreateApiKeysResponse403ResponseBody
    | CreateApiKeysResponse429ResponseBody
    | CreateApiKeysResponse500ResponseBody
    | VercelError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, CreateApiKeysResponseBody$inboundSchema),
    M.jsonErr(401, CreateApiKeysResponseResponseBody$inboundSchema),
    M.jsonErr(403, CreateApiKeysResponse403ResponseBody$inboundSchema),
    M.jsonErr(429, CreateApiKeysResponse429ResponseBody$inboundSchema),
    M.jsonErr(500, CreateApiKeysResponse500ResponseBody$inboundSchema),
    M.fail([400, 409, 410, "4XX"]),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
