/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { VercelCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/httpclienterrors.js";
import {
  ListVercelCiBranchesRequest,
  ListVercelCiBranchesRequest$outboundSchema,
  ListVercelCiBranchesResponseBody,
  ListVercelCiBranchesResponseBody$inboundSchema,
  ListVercelCiBranchesVercelCiResponse429ResponseBody,
  ListVercelCiBranchesVercelCiResponse429ResponseBody$inboundSchema,
  ListVercelCiBranchesVercelCiResponse500ResponseBody,
  ListVercelCiBranchesVercelCiResponse500ResponseBody$inboundSchema,
  ListVercelCiBranchesVercelCiResponseBody,
  ListVercelCiBranchesVercelCiResponseBody$inboundSchema,
  ListVercelCiBranchesVercelCiResponseResponseBody,
  ListVercelCiBranchesVercelCiResponseResponseBody$inboundSchema,
} from "../models/listvercelcibranchesop.js";
import { ResponseValidationError } from "../models/responsevalidationerror.js";
import { SDKValidationError } from "../models/sdkvalidationerror.js";
import { VercelError } from "../models/vercelerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * List Vercel CI branch suggestions for a team
 *
 * @remarks
 * List branches
 *
 * If set, this operation will use {@link Security.bearerToken} from the global security.
 */
export function vercelCiListVercelCiBranches(
  client: VercelCore,
  request: ListVercelCiBranchesRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    ListVercelCiBranchesResponseBody,
    | ListVercelCiBranchesVercelCiResponseBody
    | ListVercelCiBranchesVercelCiResponseResponseBody
    | ListVercelCiBranchesVercelCiResponse429ResponseBody
    | ListVercelCiBranchesVercelCiResponse500ResponseBody
    | VercelError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: VercelCore,
  request: ListVercelCiBranchesRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      ListVercelCiBranchesResponseBody,
      | ListVercelCiBranchesVercelCiResponseBody
      | ListVercelCiBranchesVercelCiResponseResponseBody
      | ListVercelCiBranchesVercelCiResponse429ResponseBody
      | ListVercelCiBranchesVercelCiResponse500ResponseBody
      | VercelError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => ListVercelCiBranchesRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const path = pathToFunc("/v2/vercel-ci/branches")();

  const query = encodeFormQuery({
    "limit": payload.limit,
    "query": payload.query,
    "slug": payload.slug,
    "teamId": payload.teamId,
  });

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.bearerToken);
  const securityInput = secConfig == null ? {} : { bearerToken: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput, [0]);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "listVercelCiBranches",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.bearerToken,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    ListVercelCiBranchesResponseBody,
    | ListVercelCiBranchesVercelCiResponseBody
    | ListVercelCiBranchesVercelCiResponseResponseBody
    | ListVercelCiBranchesVercelCiResponse429ResponseBody
    | ListVercelCiBranchesVercelCiResponse500ResponseBody
    | VercelError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, ListVercelCiBranchesResponseBody$inboundSchema),
    M.jsonErr(401, ListVercelCiBranchesVercelCiResponseBody$inboundSchema),
    M.jsonErr(
      403,
      ListVercelCiBranchesVercelCiResponseResponseBody$inboundSchema,
    ),
    M.jsonErr(
      429,
      ListVercelCiBranchesVercelCiResponse429ResponseBody$inboundSchema,
    ),
    M.jsonErr(
      500,
      ListVercelCiBranchesVercelCiResponse500ResponseBody$inboundSchema,
    ),
    M.fail([400, 404, 410, "4XX"]),
    M.fail([503, "5XX"]),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
