/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectCreateConnector } from "../funcs/connectCreateConnector.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import {
  CreateConnectorRequest,
  CreateConnectorResponse,
} from "../models/createconnectorop.js";
import { unwrapAsync } from "../types/fp.js";

export class Connect extends ClientSDK {
  /**
   * Create a connector
   *
   * @remarks
   * Create a connector and optionally link it to a project. Use `type` with complete provider data, or use `service` with `connectionMethod` so Connect can supply the type, endpoints, templates, and defaults. Production project OIDC tokens may create OAuth connectors, plus credential-less API key connectors whose credentials are supplied per user. OIDC-created connectors are automatically linked within the deployment token's eligible project environments.
   */
  async createConnector(
    request: CreateConnectorRequest,
    options?: RequestOptions,
  ): Promise<CreateConnectorResponse> {
    return unwrapAsync(connectCreateConnector(
      this,
      request,
      options,
    ));
  }
}
