// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type BatchRemoveProjectEnvRequestBody struct {
	// Array of environment variable IDs to delete
	Ids []string `json:"ids"`
}

func (o *BatchRemoveProjectEnvRequestBody) GetIds() []string {
	if o == nil {
		return []string{}
	}
	return o.Ids
}

type BatchRemoveProjectEnvRequest struct {
	// The unique project identifier or the project name
	IDOrName string `pathParam:"style=simple,explode=false,name=idOrName"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug *string                           `queryParam:"style=form,explode=true,name=slug"`
	Body *BatchRemoveProjectEnvRequestBody `request:"mediaType=application/json"`
}

func (o *BatchRemoveProjectEnvRequest) GetIDOrName() string {
	if o == nil {
		return ""
	}
	return o.IDOrName
}

func (o *BatchRemoveProjectEnvRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *BatchRemoveProjectEnvRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *BatchRemoveProjectEnvRequest) GetBody() *BatchRemoveProjectEnvRequestBody {
	if o == nil {
		return nil
	}
	return o.Body
}

type BatchRemoveProjectEnvResponseBody struct {
	Deleted float64  `json:"deleted"`
	Ids     []string `json:"ids"`
}

func (o *BatchRemoveProjectEnvResponseBody) GetDeleted() float64 {
	if o == nil {
		return 0.0
	}
	return o.Deleted
}

func (o *BatchRemoveProjectEnvResponseBody) GetIds() []string {
	if o == nil {
		return []string{}
	}
	return o.Ids
}

type BatchRemoveProjectEnvResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *BatchRemoveProjectEnvResponseBody
}

func (o *BatchRemoveProjectEnvResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *BatchRemoveProjectEnvResponse) GetObject() *BatchRemoveProjectEnvResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
