// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteRollingReleaseConfigRequest struct {
	// Project ID or project name (URL-encoded)
	IDOrName string `pathParam:"style=simple,explode=false,name=idOrName"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

func (o *DeleteRollingReleaseConfigRequest) GetIDOrName() string {
	if o == nil {
		return ""
	}
	return o.IDOrName
}

func (o *DeleteRollingReleaseConfigRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *DeleteRollingReleaseConfigRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

type DeleteRollingReleaseConfigResponseBody struct {
	RollingRelease any `json:"rollingRelease"`
}

func (o *DeleteRollingReleaseConfigResponseBody) GetRollingRelease() any {
	if o == nil {
		return nil
	}
	return o.RollingRelease
}

type DeleteRollingReleaseConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *DeleteRollingReleaseConfigResponseBody
}

func (o *DeleteRollingReleaseConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteRollingReleaseConfigResponse) GetObject() *DeleteRollingReleaseConfigResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
