// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type GetMicrofrontendsConfigForProjectRequest struct {
	// The name or ID of the project
	ProjectIDOrName string `pathParam:"style=simple,explode=false,name=projectIdOrName"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

func (o *GetMicrofrontendsConfigForProjectRequest) GetProjectIDOrName() string {
	if o == nil {
		return ""
	}
	return o.ProjectIDOrName
}

func (o *GetMicrofrontendsConfigForProjectRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *GetMicrofrontendsConfigForProjectRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

// GetMicrofrontendsConfigForProjectVersion - The version of the microfrontends config schema.
type GetMicrofrontendsConfigForProjectVersion string

const (
	GetMicrofrontendsConfigForProjectVersionOne GetMicrofrontendsConfigForProjectVersion = "1"
)

func (e GetMicrofrontendsConfigForProjectVersion) ToPointer() *GetMicrofrontendsConfigForProjectVersion {
	return &e
}
func (e *GetMicrofrontendsConfigForProjectVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "1":
		*e = GetMicrofrontendsConfigForProjectVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetMicrofrontendsConfigForProjectVersion: %v", v)
	}
}

type GetMicrofrontendsConfigForProjectLocal2Type string

const (
	GetMicrofrontendsConfigForProjectLocal2TypeStr    GetMicrofrontendsConfigForProjectLocal2Type = "str"
	GetMicrofrontendsConfigForProjectLocal2TypeNumber GetMicrofrontendsConfigForProjectLocal2Type = "number"
)

type GetMicrofrontendsConfigForProjectLocal2 struct {
	Str    *string  `queryParam:"inline"`
	Number *float64 `queryParam:"inline"`

	Type GetMicrofrontendsConfigForProjectLocal2Type
}

func CreateGetMicrofrontendsConfigForProjectLocal2Str(str string) GetMicrofrontendsConfigForProjectLocal2 {
	typ := GetMicrofrontendsConfigForProjectLocal2TypeStr

	return GetMicrofrontendsConfigForProjectLocal2{
		Str:  &str,
		Type: typ,
	}
}

func CreateGetMicrofrontendsConfigForProjectLocal2Number(number float64) GetMicrofrontendsConfigForProjectLocal2 {
	typ := GetMicrofrontendsConfigForProjectLocal2TypeNumber

	return GetMicrofrontendsConfigForProjectLocal2{
		Number: &number,
		Type:   typ,
	}
}

func (u *GetMicrofrontendsConfigForProjectLocal2) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = GetMicrofrontendsConfigForProjectLocal2TypeStr
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = GetMicrofrontendsConfigForProjectLocal2TypeNumber
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetMicrofrontendsConfigForProjectLocal2", string(data))
}

func (u GetMicrofrontendsConfigForProjectLocal2) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type GetMicrofrontendsConfigForProjectLocal2: all fields are null")
}

// GetMicrofrontendsConfigForProjectDevelopment2 - Development configuration for the child application.
type GetMicrofrontendsConfigForProjectDevelopment2 struct {
	// Fallback for local development, could point to any environment. If not provided for child apps, the fallback of the default app will be used. If passing a string, include the protocol (optional), host (required) and port (optional). For example: `https://this.ismyhost:8080`. If omitted, the protocol defaults to HTTPS. If omitted, the port defaults to `80` for HTTP and `443` for HTTPS. See https://vercel.com/docs/microfrontends/local-development.
	Fallback *string                                  `json:"fallback,omitempty"`
	Local    *GetMicrofrontendsConfigForProjectLocal2 `json:"local,omitempty"`
	// The task to run when starting the development server. Should reference a script in the package.json of the application. The default value is "dev". See https://vercel.com/docs/microfrontends/local-development.
	Task *string `json:"task,omitempty"`
}

func (g GetMicrofrontendsConfigForProjectDevelopment2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMicrofrontendsConfigForProjectDevelopment2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *GetMicrofrontendsConfigForProjectDevelopment2) GetFallback() *string {
	if o == nil {
		return nil
	}
	return o.Fallback
}

func (o *GetMicrofrontendsConfigForProjectDevelopment2) GetLocal() *GetMicrofrontendsConfigForProjectLocal2 {
	if o == nil {
		return nil
	}
	return o.Local
}

func (o *GetMicrofrontendsConfigForProjectDevelopment2) GetTask() *string {
	if o == nil {
		return nil
	}
	return o.Task
}

// GetMicrofrontendsConfigForProjectRouting - Groups of path expressions that are routed to this application. See https://vercel.com/docs/microfrontends/path-routing.
type GetMicrofrontendsConfigForProjectRouting struct {
	// Group name for the paths.
	Group *string `json:"group,omitempty"`
	// The name of the feature flag that controls routing for this group of paths. See https://vercel.com/docs/microfrontends/path-routing#routing-changes-safely-with-flags.
	Flag *string `json:"flag,omitempty"`
	// A list of path expressions that are routed to this application. See https://vercel.com/docs/microfrontends/path-routing#supported-path-expressions.
	Paths []string `json:"paths"`
}

func (g GetMicrofrontendsConfigForProjectRouting) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMicrofrontendsConfigForProjectRouting) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"paths"}); err != nil {
		return err
	}
	return nil
}

func (o *GetMicrofrontendsConfigForProjectRouting) GetGroup() *string {
	if o == nil {
		return nil
	}
	return o.Group
}

func (o *GetMicrofrontendsConfigForProjectRouting) GetFlag() *string {
	if o == nil {
		return nil
	}
	return o.Flag
}

func (o *GetMicrofrontendsConfigForProjectRouting) GetPaths() []string {
	if o == nil {
		return []string{}
	}
	return o.Paths
}

type GetMicrofrontendsConfigForProjectApplications2 struct {
	// Development configuration for the child application.
	Development *GetMicrofrontendsConfigForProjectDevelopment2 `json:"development,omitempty"`
	// Groups of path expressions that are routed to this application. See https://vercel.com/docs/microfrontends/path-routing.
	Routing []GetMicrofrontendsConfigForProjectRouting `json:"routing"`
	// The name of the asset prefix to use instead of the auto-generated name. The asset prefix is used to prefix all paths to static assets, such as JS, CSS, or images that are served by a specific application. It is necessary to ensure there are no conflicts with other applications on the same domain. An auto-generated asset prefix of the form `vc-ap-<hash>` is used when this field is not provided. When this field is provided, `/${assetPrefix}/:path*` must also be added to the list of paths in the `routing` field. Changing the asset prefix after a microfrontend application has already been deployed is not a forwards and backwards compatible change, and the asset prefix should be added to the `routing` field and deployed before setting the `assetPrefix` field. The default value is the auto-generated asset prefix of the form `vc-ap-<hash>`. See https://vercel.com/docs/microfrontends/path-routing#asset-prefix.
	AssetPrefix *string `json:"assetPrefix,omitempty"`
	// The name used to run the application, e.g. the `name` field in the `package.json`. This is used by the local proxy to map the application config to the locally running app. This is only necessary when the application name does not match the `name` used in `package.json`. See https://vercel.com/docs/microfrontends/configuration#application-naming.
	PackageName *string `json:"packageName,omitempty"`
	ProjectID   string  `json:"projectId"`
}

func (g GetMicrofrontendsConfigForProjectApplications2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMicrofrontendsConfigForProjectApplications2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"routing", "projectId"}); err != nil {
		return err
	}
	return nil
}

func (o *GetMicrofrontendsConfigForProjectApplications2) GetDevelopment() *GetMicrofrontendsConfigForProjectDevelopment2 {
	if o == nil {
		return nil
	}
	return o.Development
}

func (o *GetMicrofrontendsConfigForProjectApplications2) GetRouting() []GetMicrofrontendsConfigForProjectRouting {
	if o == nil {
		return []GetMicrofrontendsConfigForProjectRouting{}
	}
	return o.Routing
}

func (o *GetMicrofrontendsConfigForProjectApplications2) GetAssetPrefix() *string {
	if o == nil {
		return nil
	}
	return o.AssetPrefix
}

func (o *GetMicrofrontendsConfigForProjectApplications2) GetPackageName() *string {
	if o == nil {
		return nil
	}
	return o.PackageName
}

func (o *GetMicrofrontendsConfigForProjectApplications2) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

type GetMicrofrontendsConfigForProjectLocal1Type string

const (
	GetMicrofrontendsConfigForProjectLocal1TypeStr    GetMicrofrontendsConfigForProjectLocal1Type = "str"
	GetMicrofrontendsConfigForProjectLocal1TypeNumber GetMicrofrontendsConfigForProjectLocal1Type = "number"
)

type GetMicrofrontendsConfigForProjectLocal1 struct {
	Str    *string  `queryParam:"inline"`
	Number *float64 `queryParam:"inline"`

	Type GetMicrofrontendsConfigForProjectLocal1Type
}

func CreateGetMicrofrontendsConfigForProjectLocal1Str(str string) GetMicrofrontendsConfigForProjectLocal1 {
	typ := GetMicrofrontendsConfigForProjectLocal1TypeStr

	return GetMicrofrontendsConfigForProjectLocal1{
		Str:  &str,
		Type: typ,
	}
}

func CreateGetMicrofrontendsConfigForProjectLocal1Number(number float64) GetMicrofrontendsConfigForProjectLocal1 {
	typ := GetMicrofrontendsConfigForProjectLocal1TypeNumber

	return GetMicrofrontendsConfigForProjectLocal1{
		Number: &number,
		Type:   typ,
	}
}

func (u *GetMicrofrontendsConfigForProjectLocal1) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = GetMicrofrontendsConfigForProjectLocal1TypeStr
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = GetMicrofrontendsConfigForProjectLocal1TypeNumber
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetMicrofrontendsConfigForProjectLocal1", string(data))
}

func (u GetMicrofrontendsConfigForProjectLocal1) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type GetMicrofrontendsConfigForProjectLocal1: all fields are null")
}

// GetMicrofrontendsConfigForProjectDevelopment1 - Development configuration for the default application.
type GetMicrofrontendsConfigForProjectDevelopment1 struct {
	// Fallback for local development, could point to any environment. This is required for the default app. This value is used as the fallback for child apps as well if they do not have a fallback. If passing a string, include the protocol (optional), host (required) and port (optional). For example: `https://this.ismyhost:8080`. If omitted, the protocol defaults to HTTPS. If omitted, the port defaults to `80` for HTTP and `443` for HTTPS. See https://vercel.com/docs/microfrontends/local-development.
	Fallback string                                   `json:"fallback"`
	Local    *GetMicrofrontendsConfigForProjectLocal1 `json:"local,omitempty"`
	// The task to run when starting the development server. Should reference a script in the package.json of the application. The default value is "dev". See https://vercel.com/docs/microfrontends/local-development.
	Task *string `json:"task,omitempty"`
}

func (g GetMicrofrontendsConfigForProjectDevelopment1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMicrofrontendsConfigForProjectDevelopment1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"fallback"}); err != nil {
		return err
	}
	return nil
}

func (o *GetMicrofrontendsConfigForProjectDevelopment1) GetFallback() string {
	if o == nil {
		return ""
	}
	return o.Fallback
}

func (o *GetMicrofrontendsConfigForProjectDevelopment1) GetLocal() *GetMicrofrontendsConfigForProjectLocal1 {
	if o == nil {
		return nil
	}
	return o.Local
}

func (o *GetMicrofrontendsConfigForProjectDevelopment1) GetTask() *string {
	if o == nil {
		return nil
	}
	return o.Task
}

type GetMicrofrontendsConfigForProjectApplications1 struct {
	// Development configuration for the default application.
	Development GetMicrofrontendsConfigForProjectDevelopment1 `json:"development"`
	// The name used to run the application, e.g. the `name` field in the `package.json`. This is used by the local proxy to map the application config to the locally running app. This is only necessary when the application name does not match the `name` used in `package.json`. See https://vercel.com/docs/microfrontends/configuration#application-naming.
	PackageName *string `json:"packageName,omitempty"`
	ProjectID   string  `json:"projectId"`
}

func (g GetMicrofrontendsConfigForProjectApplications1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMicrofrontendsConfigForProjectApplications1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"development", "projectId"}); err != nil {
		return err
	}
	return nil
}

func (o *GetMicrofrontendsConfigForProjectApplications1) GetDevelopment() GetMicrofrontendsConfigForProjectDevelopment1 {
	if o == nil {
		return GetMicrofrontendsConfigForProjectDevelopment1{}
	}
	return o.Development
}

func (o *GetMicrofrontendsConfigForProjectApplications1) GetPackageName() *string {
	if o == nil {
		return nil
	}
	return o.PackageName
}

func (o *GetMicrofrontendsConfigForProjectApplications1) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

type GetMicrofrontendsConfigForProjectApplicationsUnionType string

const (
	GetMicrofrontendsConfigForProjectApplicationsUnionTypeGetMicrofrontendsConfigForProjectApplications1 GetMicrofrontendsConfigForProjectApplicationsUnionType = "getMicrofrontendsConfigForProject_applications_1"
	GetMicrofrontendsConfigForProjectApplicationsUnionTypeGetMicrofrontendsConfigForProjectApplications2 GetMicrofrontendsConfigForProjectApplicationsUnionType = "getMicrofrontendsConfigForProject_applications_2"
)

type GetMicrofrontendsConfigForProjectApplicationsUnion struct {
	GetMicrofrontendsConfigForProjectApplications1 *GetMicrofrontendsConfigForProjectApplications1 `queryParam:"inline"`
	GetMicrofrontendsConfigForProjectApplications2 *GetMicrofrontendsConfigForProjectApplications2 `queryParam:"inline"`

	Type GetMicrofrontendsConfigForProjectApplicationsUnionType
}

func CreateGetMicrofrontendsConfigForProjectApplicationsUnionGetMicrofrontendsConfigForProjectApplications1(getMicrofrontendsConfigForProjectApplications1 GetMicrofrontendsConfigForProjectApplications1) GetMicrofrontendsConfigForProjectApplicationsUnion {
	typ := GetMicrofrontendsConfigForProjectApplicationsUnionTypeGetMicrofrontendsConfigForProjectApplications1

	return GetMicrofrontendsConfigForProjectApplicationsUnion{
		GetMicrofrontendsConfigForProjectApplications1: &getMicrofrontendsConfigForProjectApplications1,
		Type: typ,
	}
}

func CreateGetMicrofrontendsConfigForProjectApplicationsUnionGetMicrofrontendsConfigForProjectApplications2(getMicrofrontendsConfigForProjectApplications2 GetMicrofrontendsConfigForProjectApplications2) GetMicrofrontendsConfigForProjectApplicationsUnion {
	typ := GetMicrofrontendsConfigForProjectApplicationsUnionTypeGetMicrofrontendsConfigForProjectApplications2

	return GetMicrofrontendsConfigForProjectApplicationsUnion{
		GetMicrofrontendsConfigForProjectApplications2: &getMicrofrontendsConfigForProjectApplications2,
		Type: typ,
	}
}

func (u *GetMicrofrontendsConfigForProjectApplicationsUnion) UnmarshalJSON(data []byte) error {

	var getMicrofrontendsConfigForProjectApplications1 GetMicrofrontendsConfigForProjectApplications1 = GetMicrofrontendsConfigForProjectApplications1{}
	if err := utils.UnmarshalJSON(data, &getMicrofrontendsConfigForProjectApplications1, "", true, nil); err == nil {
		u.GetMicrofrontendsConfigForProjectApplications1 = &getMicrofrontendsConfigForProjectApplications1
		u.Type = GetMicrofrontendsConfigForProjectApplicationsUnionTypeGetMicrofrontendsConfigForProjectApplications1
		return nil
	}

	var getMicrofrontendsConfigForProjectApplications2 GetMicrofrontendsConfigForProjectApplications2 = GetMicrofrontendsConfigForProjectApplications2{}
	if err := utils.UnmarshalJSON(data, &getMicrofrontendsConfigForProjectApplications2, "", true, nil); err == nil {
		u.GetMicrofrontendsConfigForProjectApplications2 = &getMicrofrontendsConfigForProjectApplications2
		u.Type = GetMicrofrontendsConfigForProjectApplicationsUnionTypeGetMicrofrontendsConfigForProjectApplications2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetMicrofrontendsConfigForProjectApplicationsUnion", string(data))
}

func (u GetMicrofrontendsConfigForProjectApplicationsUnion) MarshalJSON() ([]byte, error) {
	if u.GetMicrofrontendsConfigForProjectApplications1 != nil {
		return utils.MarshalJSON(u.GetMicrofrontendsConfigForProjectApplications1, "", true)
	}

	if u.GetMicrofrontendsConfigForProjectApplications2 != nil {
		return utils.MarshalJSON(u.GetMicrofrontendsConfigForProjectApplications2, "", true)
	}

	return nil, errors.New("could not marshal union type GetMicrofrontendsConfigForProjectApplicationsUnion: all fields are null")
}

// GetMicrofrontendsConfigForProjectOptions - Optional configuration options for the microfrontend.
type GetMicrofrontendsConfigForProjectOptions struct {
	// If you want to disable the overrides for the site. For example, if you are managing rewrites between applications externally, you may wish to disable the overrides on the toolbar as they will have no effect. See https://vercel.com/docs/microfrontends/managing-microfrontends/vercel-toolbar#routing-overrides.
	DisableOverrides *bool `json:"disableOverrides,omitempty"`
	// The port number used by the local proxy server. The default value is 3024. See https://vercel.com/docs/microfrontends/local-development.
	LocalProxyPort *float64 `json:"localProxyPort,omitempty"`
}

func (o *GetMicrofrontendsConfigForProjectOptions) GetDisableOverrides() *bool {
	if o == nil {
		return nil
	}
	return o.DisableOverrides
}

func (o *GetMicrofrontendsConfigForProjectOptions) GetLocalProxyPort() *float64 {
	if o == nil {
		return nil
	}
	return o.LocalProxyPort
}

// GetMicrofrontendsConfigForProjectConfig - projectIds are added when the config is uploaded to s3 deployment assets.
type GetMicrofrontendsConfigForProjectConfig struct {
	// See https://openapi.vercel.sh/microfrontends.json.
	DollarSchema *string `json:"$schema,omitempty"`
	// The version of the microfrontends config schema.
	Version      *GetMicrofrontendsConfigForProjectVersion                     `json:"version,omitempty"`
	Applications map[string]GetMicrofrontendsConfigForProjectApplicationsUnion `json:"applications"`
	// Optional configuration options for the microfrontend.
	Options *GetMicrofrontendsConfigForProjectOptions `json:"options,omitempty"`
}

func (o *GetMicrofrontendsConfigForProjectConfig) GetDollarSchema() *string {
	if o == nil {
		return nil
	}
	return o.DollarSchema
}

func (o *GetMicrofrontendsConfigForProjectConfig) GetVersion() *GetMicrofrontendsConfigForProjectVersion {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *GetMicrofrontendsConfigForProjectConfig) GetApplications() map[string]GetMicrofrontendsConfigForProjectApplicationsUnion {
	if o == nil {
		return map[string]GetMicrofrontendsConfigForProjectApplicationsUnion{}
	}
	return o.Applications
}

func (o *GetMicrofrontendsConfigForProjectConfig) GetOptions() *GetMicrofrontendsConfigForProjectOptions {
	if o == nil {
		return nil
	}
	return o.Options
}

type GetMicrofrontendsConfigForProjectResponseBody struct {
	// projectIds are added when the config is uploaded to s3 deployment assets.
	Config *GetMicrofrontendsConfigForProjectConfig `json:"config"`
}

func (o *GetMicrofrontendsConfigForProjectResponseBody) GetConfig() *GetMicrofrontendsConfigForProjectConfig {
	if o == nil {
		return nil
	}
	return o.Config
}

type GetMicrofrontendsConfigForProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *GetMicrofrontendsConfigForProjectResponseBody
}

func (o *GetMicrofrontendsConfigForProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetMicrofrontendsConfigForProjectResponse) GetObject() *GetMicrofrontendsConfigForProjectResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
