// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
)

type ListAccessGroupMembersRequest struct {
	// The ID or name of the Access Group.
	IDOrName string `pathParam:"style=simple,explode=false,name=idOrName"`
	// Limit how many access group members should be returned.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Continuation cursor to retrieve the next page of results.
	Next *string `queryParam:"style=form,explode=true,name=next"`
	// Search project members by their name, username, and email.
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

func (o *ListAccessGroupMembersRequest) GetIDOrName() string {
	if o == nil {
		return ""
	}
	return o.IDOrName
}

func (o *ListAccessGroupMembersRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListAccessGroupMembersRequest) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ListAccessGroupMembersRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *ListAccessGroupMembersRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *ListAccessGroupMembersRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

type ListAccessGroupMembersTeamRole string

const (
	ListAccessGroupMembersTeamRoleOwner       ListAccessGroupMembersTeamRole = "OWNER"
	ListAccessGroupMembersTeamRoleMember      ListAccessGroupMembersTeamRole = "MEMBER"
	ListAccessGroupMembersTeamRoleDeveloper   ListAccessGroupMembersTeamRole = "DEVELOPER"
	ListAccessGroupMembersTeamRoleSecurity    ListAccessGroupMembersTeamRole = "SECURITY"
	ListAccessGroupMembersTeamRoleBilling     ListAccessGroupMembersTeamRole = "BILLING"
	ListAccessGroupMembersTeamRoleViewer      ListAccessGroupMembersTeamRole = "VIEWER"
	ListAccessGroupMembersTeamRoleContributor ListAccessGroupMembersTeamRole = "CONTRIBUTOR"
)

func (e ListAccessGroupMembersTeamRole) ToPointer() *ListAccessGroupMembersTeamRole {
	return &e
}
func (e *ListAccessGroupMembersTeamRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OWNER":
		fallthrough
	case "MEMBER":
		fallthrough
	case "DEVELOPER":
		fallthrough
	case "SECURITY":
		fallthrough
	case "BILLING":
		fallthrough
	case "VIEWER":
		fallthrough
	case "CONTRIBUTOR":
		*e = ListAccessGroupMembersTeamRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListAccessGroupMembersTeamRole: %v", v)
	}
}

type ListAccessGroupMembersMember struct {
	Avatar    *string                        `json:"avatar,omitempty"`
	Email     string                         `json:"email"`
	UID       string                         `json:"uid"`
	Username  string                         `json:"username"`
	Name      *string                        `json:"name,omitempty"`
	CreatedAt *string                        `json:"createdAt,omitempty"`
	TeamRole  ListAccessGroupMembersTeamRole `json:"teamRole"`
}

func (o *ListAccessGroupMembersMember) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *ListAccessGroupMembersMember) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *ListAccessGroupMembersMember) GetUID() string {
	if o == nil {
		return ""
	}
	return o.UID
}

func (o *ListAccessGroupMembersMember) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *ListAccessGroupMembersMember) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ListAccessGroupMembersMember) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *ListAccessGroupMembersMember) GetTeamRole() ListAccessGroupMembersTeamRole {
	if o == nil {
		return ListAccessGroupMembersTeamRole("")
	}
	return o.TeamRole
}

type ListAccessGroupMembersPagination struct {
	Count float64 `json:"count"`
	Next  *string `json:"next"`
}

func (o *ListAccessGroupMembersPagination) GetCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Count
}

func (o *ListAccessGroupMembersPagination) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

type ListAccessGroupMembersResponseBody struct {
	Members    []ListAccessGroupMembersMember   `json:"members"`
	Pagination ListAccessGroupMembersPagination `json:"pagination"`
}

func (o *ListAccessGroupMembersResponseBody) GetMembers() []ListAccessGroupMembersMember {
	if o == nil {
		return []ListAccessGroupMembersMember{}
	}
	return o.Members
}

func (o *ListAccessGroupMembersResponseBody) GetPagination() ListAccessGroupMembersPagination {
	if o == nil {
		return ListAccessGroupMembersPagination{}
	}
	return o.Pagination
}

type ListAccessGroupMembersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListAccessGroupMembersResponseBody
}

func (o *ListAccessGroupMembersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListAccessGroupMembersResponse) GetObject() *ListAccessGroupMembersResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
