// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type StopSandboxRequest struct {
	// The unique identifier of the sandbox to stop.
	SandboxID string `pathParam:"style=simple,explode=false,name=sandboxId"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

func (o *StopSandboxRequest) GetSandboxID() string {
	if o == nil {
		return ""
	}
	return o.SandboxID
}

func (o *StopSandboxRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *StopSandboxRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

// StopSandboxResponseBody - The sandbox was stopped successfully.
type StopSandboxResponseBody struct {
	// This object contains information related to a Vercel Sandbox.
	Sandbox components.Sandbox `json:"sandbox"`
}

func (o *StopSandboxResponseBody) GetSandbox() components.Sandbox {
	if o == nil {
		return components.Sandbox{}
	}
	return o.Sandbox
}

type StopSandboxResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The sandbox was stopped successfully.
	Object *StopSandboxResponseBody
}

func (o *StopSandboxResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *StopSandboxResponse) GetObject() *StopSandboxResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
