// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateMicrofrontendsGroupRequestBody struct {
	// The new name for the existing microfrontends group.
	Name *string `json:"name,omitempty"`
	// The new fallback environment for the microfrontends group. Must be \"SAME_ENV\", \"PRODUCTION\", or a valid custom environment slug from the default app.
	FallbackEnvironment *string `json:"fallbackEnvironment,omitempty"`
}

func (o *UpdateMicrofrontendsGroupRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateMicrofrontendsGroupRequestBody) GetFallbackEnvironment() *string {
	if o == nil {
		return nil
	}
	return o.FallbackEnvironment
}

type UpdateMicrofrontendsGroupRequest struct {
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
	// The Team identifier to perform the request on behalf of.
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug *string                               `queryParam:"style=form,explode=true,name=slug"`
	Body *UpdateMicrofrontendsGroupRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateMicrofrontendsGroupRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

func (o *UpdateMicrofrontendsGroupRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *UpdateMicrofrontendsGroupRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *UpdateMicrofrontendsGroupRequest) GetBody() *UpdateMicrofrontendsGroupRequestBody {
	if o == nil {
		return nil
	}
	return o.Body
}

type UpdatedMicrofrontendsGroup struct {
	Name                *string `json:"name,omitempty"`
	Slug                *string `json:"slug,omitempty"`
	ID                  string  `json:"id"`
	FallbackEnvironment *string `json:"fallbackEnvironment,omitempty"`
}

func (o *UpdatedMicrofrontendsGroup) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdatedMicrofrontendsGroup) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *UpdatedMicrofrontendsGroup) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdatedMicrofrontendsGroup) GetFallbackEnvironment() *string {
	if o == nil {
		return nil
	}
	return o.FallbackEnvironment
}

type UpdateMicrofrontendsGroupResponseBody struct {
	UpdatedMicrofrontendsGroup UpdatedMicrofrontendsGroup `json:"updatedMicrofrontendsGroup"`
}

func (o *UpdateMicrofrontendsGroupResponseBody) GetUpdatedMicrofrontendsGroup() UpdatedMicrofrontendsGroup {
	if o == nil {
		return UpdatedMicrofrontendsGroup{}
	}
	return o.UpdatedMicrofrontendsGroup
}

type UpdateMicrofrontendsGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *UpdateMicrofrontendsGroupResponseBody
}

func (o *UpdateMicrofrontendsGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateMicrofrontendsGroupResponse) GetObject() *UpdateMicrofrontendsGroupResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
