// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DomainNotFoundCode string

const (
	DomainNotFoundCodeDomainNotFound DomainNotFoundCode = "domain_not_found"
)

func (e DomainNotFoundCode) ToPointer() *DomainNotFoundCode {
	return &e
}
func (e *DomainNotFoundCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "domain_not_found":
		*e = DomainNotFoundCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DomainNotFoundCode: %v", v)
	}
}
