// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// HostedZones - Metadata about any AWS Route53 Hosted Zones associated with the Network.
type HostedZones struct {
	// The number of AWS Route53 Hosted Zones associated with the Network.
	Count float64 `json:"count"`
}

func (o *HostedZones) GetCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Count
}

// PeeringConnections - Metadata about any AWS Route53 Hosted Zones associated with the Network.
type PeeringConnections struct {
	// The number of AWS Route53 Hosted Zones associated with the Network.
	Count float64 `json:"count"`
}

func (o *PeeringConnections) GetCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Count
}

// Projects - Metadata about any projects associated with the Network.
type Projects struct {
	Count float64  `json:"count"`
	Ids   []string `json:"ids"`
}

func (o *Projects) GetCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Count
}

func (o *Projects) GetIds() []string {
	if o == nil {
		return []string{}
	}
	return o.Ids
}

// Status - The status of the Network.
type Status string

const (
	StatusCreateInProgress Status = "create_in_progress"
	StatusDeleteInProgress Status = "delete_in_progress"
	StatusError            Status = "error"
	StatusReady            Status = "ready"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "create_in_progress":
		fallthrough
	case "delete_in_progress":
		fallthrough
	case "error":
		fallthrough
	case "ready":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type Network struct {
	// The ID of the AWS Account in which the network exists.
	AwsAccountID string `json:"awsAccountId"`
	// The IDs of the AWS Availability Zones in which the network exists, if specified during creation.
	AwsAvailabilityZoneIds []string `json:"awsAvailabilityZoneIds,omitempty"`
	// The AWS Region in which the network exists.
	AwsRegion string `json:"awsRegion"`
	// The CIDR range of the Network.
	Cidr string `json:"cidr"`
	// The date at which the Network was created, represented as a UNIX timestamp since EPOCH.
	CreatedAt         float64  `json:"createdAt"`
	EgressIPAddresses []string `json:"egressIpAddresses,omitempty"`
	// Metadata about any AWS Route53 Hosted Zones associated with the Network.
	HostedZones *HostedZones `json:"hostedZones,omitempty"`
	// The unique identifier of the Network.
	ID string `json:"id"`
	// The name of the network.
	Name string `json:"name"`
	// Metadata about any AWS Route53 Hosted Zones associated with the Network.
	PeeringConnections *PeeringConnections `json:"peeringConnections,omitempty"`
	// Metadata about any projects associated with the Network.
	Projects *Projects `json:"projects,omitempty"`
	// The Vercel region in which the Network exists.
	Region *string `json:"region,omitempty"`
	// The status of the Network.
	Status Status `json:"status"`
	// The unique identifier of the Team that owns the Network.
	TeamID string `json:"teamId"`
	// The ID of the VPC which hosts the network.
	VpcID *string `json:"vpcId,omitempty"`
}

func (o *Network) GetAwsAccountID() string {
	if o == nil {
		return ""
	}
	return o.AwsAccountID
}

func (o *Network) GetAwsAvailabilityZoneIds() []string {
	if o == nil {
		return nil
	}
	return o.AwsAvailabilityZoneIds
}

func (o *Network) GetAwsRegion() string {
	if o == nil {
		return ""
	}
	return o.AwsRegion
}

func (o *Network) GetCidr() string {
	if o == nil {
		return ""
	}
	return o.Cidr
}

func (o *Network) GetCreatedAt() float64 {
	if o == nil {
		return 0.0
	}
	return o.CreatedAt
}

func (o *Network) GetEgressIPAddresses() []string {
	if o == nil {
		return nil
	}
	return o.EgressIPAddresses
}

func (o *Network) GetHostedZones() *HostedZones {
	if o == nil {
		return nil
	}
	return o.HostedZones
}

func (o *Network) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Network) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Network) GetPeeringConnections() *PeeringConnections {
	if o == nil {
		return nil
	}
	return o.PeeringConnections
}

func (o *Network) GetProjects() *Projects {
	if o == nil {
		return nil
	}
	return o.Projects
}

func (o *Network) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *Network) GetStatus() Status {
	if o == nil {
		return Status("")
	}
	return o.Status
}

func (o *Network) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *Network) GetVpcID() *string {
	if o == nil {
		return nil
	}
	return o.VpcID
}
