// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type OrderTooExpensiveCode string

const (
	OrderTooExpensiveCodeOrderTooExpensive OrderTooExpensiveCode = "order_too_expensive"
)

func (e OrderTooExpensiveCode) ToPointer() *OrderTooExpensiveCode {
	return &e
}
func (e *OrderTooExpensiveCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "order_too_expensive":
		*e = OrderTooExpensiveCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrderTooExpensiveCode: %v", v)
	}
}
