// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TldNotSupportedCode string

const (
	TldNotSupportedCodeTldNotSupported TldNotSupportedCode = "tld_not_supported"
)

func (e TldNotSupportedCode) ToPointer() *TldNotSupportedCode {
	return &e
}
func (e *TldNotSupportedCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tld_not_supported":
		*e = TldNotSupportedCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TldNotSupportedCode: %v", v)
	}
}
