/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type CompleteRollingReleaseRequestBody = {
  /**
   * The ID of the canary deployment to complete
   */
  canaryDeploymentId: string;
};

export type CompleteRollingReleaseRequest = {
  /**
   * Project ID or project name (URL-encoded)
   */
  idOrName: string;
  /**
   * The Team identifier to perform the request on behalf of.
   */
  teamId?: string | undefined;
  /**
   * The Team slug to perform the request on behalf of.
   */
  slug?: string | undefined;
  requestBody?: CompleteRollingReleaseRequestBody | undefined;
};

/**
 * The currently active stage, null if the rollout is aborted
 */
export type CompleteRollingReleaseActiveStage = {
  /**
   * Duration in seconds for automatic advancement, null for manual stages or the final stage
   */
  duration: number | null;
  /**
   * The zero-based index of the stage
   */
  index: number;
  /**
   * Whether or not this stage is the final stage (targetPercentage === 100)
   */
  isFinalStage: boolean;
  /**
   * Whether to linearly shift traffic over the duration of this stage
   */
  linearShift?: boolean | undefined;
  /**
   * Whether or not this stage requires manual approval to proceed
   */
  requireApproval: boolean;
  /**
   * The percentage of traffic to serve to the canary deployment (0-100)
   */
  targetPercentage: number;
};

/**
 * The advancement type of the rolling release
 */
export const CompleteRollingReleaseAdvancementType = {
  Automatic: "automatic",
  ManualApproval: "manual-approval",
} as const;
/**
 * The advancement type of the rolling release
 */
export type CompleteRollingReleaseAdvancementType = ClosedEnum<
  typeof CompleteRollingReleaseAdvancementType
>;

/**
 * The state of the deployment depending on the process of deploying, or if it is ready or in an error state
 */
export const CompleteRollingReleaseReadyState = {
  Blocked: "BLOCKED",
  Building: "BUILDING",
  Canceled: "CANCELED",
  Error: "ERROR",
  Initializing: "INITIALIZING",
  Queued: "QUEUED",
  Ready: "READY",
} as const;
/**
 * The state of the deployment depending on the process of deploying, or if it is ready or in an error state
 */
export type CompleteRollingReleaseReadyState = ClosedEnum<
  typeof CompleteRollingReleaseReadyState
>;

/**
 * Where was the deployment created from. Best-effort guess for metrics only — not authoritative; do not gate behavior on it.
 */
export const CompleteRollingReleaseSource = {
  ApiTriggerGitDeploy: "api-trigger-git-deploy",
  Cli: "cli",
  CloneRepo: "clone/repo",
  Drop: "drop",
  Git: "git",
  GitDeployHook: "git-deploy-hook",
  Import: "import",
  ImportRepo: "import/repo",
  Redeploy: "redeploy",
  V0Web: "v0-web",
} as const;
/**
 * Where was the deployment created from. Best-effort guess for metrics only — not authoritative; do not gate behavior on it.
 */
export type CompleteRollingReleaseSource = ClosedEnum<
  typeof CompleteRollingReleaseSource
>;

/**
 * If defined, either `staging` if a staging alias in the format `<project>.<team>.now.sh` was assigned upon creation, or `production` if the aliases from `alias` were assigned. `null` value indicates the "preview" deployment.
 */
export const CompleteRollingReleaseTarget = {
  Production: "production",
  Staging: "staging",
} as const;
/**
 * If defined, either `staging` if a staging alias in the format `<project>.<team>.now.sh` was assigned upon creation, or `production` if the aliases from `alias` were assigned. `null` value indicates the "preview" deployment.
 */
export type CompleteRollingReleaseTarget = ClosedEnum<
  typeof CompleteRollingReleaseTarget
>;

/**
 * The canary deployment being rolled out
 */
export type CompleteRollingReleaseCanaryDeployment = {
  /**
   * A number containing the date when the deployment was created in milliseconds
   */
  createdAt: number;
  /**
   * A string holding the unique ID of the deployment
   */
  id: string;
  /**
   * The name of the project associated with the deployment at the time that the deployment was created
   */
  name: string;
  /**
   * The state of the deployment depending on the process of deploying, or if it is ready or in an error state
   */
  readyState: CompleteRollingReleaseReadyState;
  readyStateAt?: number | undefined;
  /**
   * Where was the deployment created from. Best-effort guess for metrics only — not authoritative; do not gate behavior on it.
   */
  source?: CompleteRollingReleaseSource | undefined;
  /**
   * If defined, either `staging` if a staging alias in the format `<project>.<team>.now.sh` was assigned upon creation, or `production` if the aliases from `alias` were assigned. `null` value indicates the "preview" deployment.
   */
  target?: CompleteRollingReleaseTarget | null | undefined;
  /**
   * A string with the unique URL of the deployment
   */
  url: string;
};

/**
 * The state of the deployment depending on the process of deploying, or if it is ready or in an error state
 */
export const CompleteRollingReleaseRollingReleaseReadyState = {
  Blocked: "BLOCKED",
  Building: "BUILDING",
  Canceled: "CANCELED",
  Error: "ERROR",
  Initializing: "INITIALIZING",
  Queued: "QUEUED",
  Ready: "READY",
} as const;
/**
 * The state of the deployment depending on the process of deploying, or if it is ready or in an error state
 */
export type CompleteRollingReleaseRollingReleaseReadyState = ClosedEnum<
  typeof CompleteRollingReleaseRollingReleaseReadyState
>;

/**
 * Where was the deployment created from. Best-effort guess for metrics only — not authoritative; do not gate behavior on it.
 */
export const CompleteRollingReleaseRollingReleaseSource = {
  ApiTriggerGitDeploy: "api-trigger-git-deploy",
  Cli: "cli",
  CloneRepo: "clone/repo",
  Drop: "drop",
  Git: "git",
  GitDeployHook: "git-deploy-hook",
  Import: "import",
  ImportRepo: "import/repo",
  Redeploy: "redeploy",
  V0Web: "v0-web",
} as const;
/**
 * Where was the deployment created from. Best-effort guess for metrics only — not authoritative; do not gate behavior on it.
 */
export type CompleteRollingReleaseRollingReleaseSource = ClosedEnum<
  typeof CompleteRollingReleaseRollingReleaseSource
>;

/**
 * If defined, either `staging` if a staging alias in the format `<project>.<team>.now.sh` was assigned upon creation, or `production` if the aliases from `alias` were assigned. `null` value indicates the "preview" deployment.
 */
export const CompleteRollingReleaseRollingReleaseTarget = {
  Production: "production",
  Staging: "staging",
} as const;
/**
 * If defined, either `staging` if a staging alias in the format `<project>.<team>.now.sh` was assigned upon creation, or `production` if the aliases from `alias` were assigned. `null` value indicates the "preview" deployment.
 */
export type CompleteRollingReleaseRollingReleaseTarget = ClosedEnum<
  typeof CompleteRollingReleaseRollingReleaseTarget
>;

/**
 * The current deployment receiving production traffic
 */
export type CompleteRollingReleaseCurrentDeployment = {
  /**
   * A number containing the date when the deployment was created in milliseconds
   */
  createdAt: number;
  /**
   * A string holding the unique ID of the deployment
   */
  id: string;
  /**
   * The name of the project associated with the deployment at the time that the deployment was created
   */
  name: string;
  /**
   * The state of the deployment depending on the process of deploying, or if it is ready or in an error state
   */
  readyState: CompleteRollingReleaseRollingReleaseReadyState;
  readyStateAt?: number | undefined;
  /**
   * Where was the deployment created from. Best-effort guess for metrics only — not authoritative; do not gate behavior on it.
   */
  source?: CompleteRollingReleaseRollingReleaseSource | undefined;
  /**
   * If defined, either `staging` if a staging alias in the format `<project>.<team>.now.sh` was assigned upon creation, or `production` if the aliases from `alias` were assigned. `null` value indicates the "preview" deployment.
   */
  target?: CompleteRollingReleaseRollingReleaseTarget | null | undefined;
  /**
   * A string with the unique URL of the deployment
   */
  url: string;
};

/**
 * The next stage to be activated, null if not in ACTIVE state
 */
export type CompleteRollingReleaseNextStage = {
  /**
   * Duration in seconds for automatic advancement, null for manual stages or the final stage
   */
  duration: number | null;
  /**
   * The zero-based index of the stage
   */
  index: number;
  /**
   * Whether or not this stage is the final stage (targetPercentage === 100)
   */
  isFinalStage: boolean;
  /**
   * Whether to linearly shift traffic over the duration of this stage
   */
  linearShift?: boolean | undefined;
  /**
   * Whether or not this stage requires manual approval to proceed
   */
  requireApproval: boolean;
  /**
   * The percentage of traffic to serve to the canary deployment (0-100)
   */
  targetPercentage: number;
};

/**
 * All stages configured for this rolling release
 */
export type CompleteRollingReleaseStages = {
  /**
   * Duration in seconds for automatic advancement, null for manual stages or the final stage
   */
  duration: number | null;
  /**
   * The zero-based index of the stage
   */
  index: number;
  /**
   * Whether or not this stage is the final stage (targetPercentage === 100)
   */
  isFinalStage: boolean;
  /**
   * Whether to linearly shift traffic over the duration of this stage
   */
  linearShift?: boolean | undefined;
  /**
   * Whether or not this stage requires manual approval to proceed
   */
  requireApproval: boolean;
  /**
   * The percentage of traffic to serve to the canary deployment (0-100)
   */
  targetPercentage: number;
};

/**
 * The current state of the rolling release
 */
export const CompleteRollingReleaseState = {
  Aborted: "ABORTED",
  Active: "ACTIVE",
  Complete: "COMPLETE",
} as const;
/**
 * The current state of the rolling release
 */
export type CompleteRollingReleaseState = ClosedEnum<
  typeof CompleteRollingReleaseState
>;

/**
 * When set to `PAUSED`, the rollout is frozen at the current percentage until continued.
 */
export const CompleteRollingReleaseSubstate = {
  Paused: "PAUSED",
} as const;
/**
 * When set to `PAUSED`, the rollout is frozen at the current percentage until continued.
 */
export type CompleteRollingReleaseSubstate = ClosedEnum<
  typeof CompleteRollingReleaseSubstate
>;

/**
 * Rolling release information including configuration and document details, or null if no rolling release exists
 */
export type CompleteRollingReleaseRollingRelease = {
  /**
   * The currently active stage, null if the rollout is aborted
   */
  activeStage: CompleteRollingReleaseActiveStage | null;
  /**
   * The advancement type of the rolling release
   */
  advancementType: CompleteRollingReleaseAdvancementType;
  /**
   * The canary deployment being rolled out
   */
  canaryDeployment: CompleteRollingReleaseCanaryDeployment | null;
  /**
   * When set (for example while {@link substate} is `PAUSED`), the canary traffic percentage persisted on the rollout document — use for dashboard display when linear shift is active.
   */
  currentCanaryPercentage?: number | undefined;
  /**
   * The current deployment receiving production traffic
   */
  currentDeployment: CompleteRollingReleaseCurrentDeployment | null;
  /**
   * The next stage to be activated, null if not in ACTIVE state
   */
  nextStage: CompleteRollingReleaseNextStage | null;
  /**
   * The ID of a deployment queued for the next rolling release
   */
  queuedDeploymentId: string | null;
  /**
   * All stages configured for this rolling release
   */
  stages: Array<CompleteRollingReleaseStages>;
  /**
   * Unix timestamp in milliseconds when the rolling release started
   */
  startedAt: number;
  /**
   * The current state of the rolling release
   */
  state: CompleteRollingReleaseState;
  /**
   * When set to `PAUSED`, the rollout is frozen at the current percentage until continued.
   */
  substate: CompleteRollingReleaseSubstate | null;
  /**
   * Unix timestamp in milliseconds when the rolling release was last updated
   */
  updatedAt: number;
};

/**
 * The response format for rolling release endpoints that return rolling release information
 */
export type CompleteRollingReleaseResponseBody = {
  /**
   * Rolling release information including configuration and document details, or null if no rolling release exists
   */
  rollingRelease: CompleteRollingReleaseRollingRelease | null;
};

/** @internal */
export type CompleteRollingReleaseRequestBody$Outbound = {
  canaryDeploymentId: string;
};

/** @internal */
export const CompleteRollingReleaseRequestBody$outboundSchema: z.ZodType<
  CompleteRollingReleaseRequestBody$Outbound,
  z.ZodTypeDef,
  CompleteRollingReleaseRequestBody
> = z.object({
  canaryDeploymentId: z.string(),
});

export function completeRollingReleaseRequestBodyToJSON(
  completeRollingReleaseRequestBody: CompleteRollingReleaseRequestBody,
): string {
  return JSON.stringify(
    CompleteRollingReleaseRequestBody$outboundSchema.parse(
      completeRollingReleaseRequestBody,
    ),
  );
}

/** @internal */
export type CompleteRollingReleaseRequest$Outbound = {
  idOrName: string;
  teamId?: string | undefined;
  slug?: string | undefined;
  RequestBody?: CompleteRollingReleaseRequestBody$Outbound | undefined;
};

/** @internal */
export const CompleteRollingReleaseRequest$outboundSchema: z.ZodType<
  CompleteRollingReleaseRequest$Outbound,
  z.ZodTypeDef,
  CompleteRollingReleaseRequest
> = z.object({
  idOrName: z.string(),
  teamId: z.string().optional(),
  slug: z.string().optional(),
  requestBody: z.lazy(() => CompleteRollingReleaseRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function completeRollingReleaseRequestToJSON(
  completeRollingReleaseRequest: CompleteRollingReleaseRequest,
): string {
  return JSON.stringify(
    CompleteRollingReleaseRequest$outboundSchema.parse(
      completeRollingReleaseRequest,
    ),
  );
}

/** @internal */
export const CompleteRollingReleaseActiveStage$inboundSchema: z.ZodType<
  CompleteRollingReleaseActiveStage,
  z.ZodTypeDef,
  unknown
> = z.object({
  duration: types.nullable(types.number()),
  index: types.number(),
  isFinalStage: types.boolean(),
  linearShift: types.optional(types.boolean()),
  requireApproval: types.boolean(),
  targetPercentage: types.number(),
});

export function completeRollingReleaseActiveStageFromJSON(
  jsonString: string,
): SafeParseResult<CompleteRollingReleaseActiveStage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompleteRollingReleaseActiveStage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompleteRollingReleaseActiveStage' from JSON`,
  );
}

/** @internal */
export const CompleteRollingReleaseAdvancementType$inboundSchema:
  z.ZodNativeEnum<typeof CompleteRollingReleaseAdvancementType> = z.nativeEnum(
    CompleteRollingReleaseAdvancementType,
  );

/** @internal */
export const CompleteRollingReleaseReadyState$inboundSchema: z.ZodNativeEnum<
  typeof CompleteRollingReleaseReadyState
> = z.nativeEnum(CompleteRollingReleaseReadyState);

/** @internal */
export const CompleteRollingReleaseSource$inboundSchema: z.ZodNativeEnum<
  typeof CompleteRollingReleaseSource
> = z.nativeEnum(CompleteRollingReleaseSource);

/** @internal */
export const CompleteRollingReleaseTarget$inboundSchema: z.ZodNativeEnum<
  typeof CompleteRollingReleaseTarget
> = z.nativeEnum(CompleteRollingReleaseTarget);

/** @internal */
export const CompleteRollingReleaseCanaryDeployment$inboundSchema: z.ZodType<
  CompleteRollingReleaseCanaryDeployment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: types.number(),
  id: types.string(),
  name: types.string(),
  readyState: CompleteRollingReleaseReadyState$inboundSchema,
  readyStateAt: types.optional(types.number()),
  source: types.optional(CompleteRollingReleaseSource$inboundSchema),
  target: z.nullable(CompleteRollingReleaseTarget$inboundSchema).optional(),
  url: types.string(),
});

export function completeRollingReleaseCanaryDeploymentFromJSON(
  jsonString: string,
): SafeParseResult<CompleteRollingReleaseCanaryDeployment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CompleteRollingReleaseCanaryDeployment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompleteRollingReleaseCanaryDeployment' from JSON`,
  );
}

/** @internal */
export const CompleteRollingReleaseRollingReleaseReadyState$inboundSchema:
  z.ZodNativeEnum<typeof CompleteRollingReleaseRollingReleaseReadyState> = z
    .nativeEnum(CompleteRollingReleaseRollingReleaseReadyState);

/** @internal */
export const CompleteRollingReleaseRollingReleaseSource$inboundSchema:
  z.ZodNativeEnum<typeof CompleteRollingReleaseRollingReleaseSource> = z
    .nativeEnum(CompleteRollingReleaseRollingReleaseSource);

/** @internal */
export const CompleteRollingReleaseRollingReleaseTarget$inboundSchema:
  z.ZodNativeEnum<typeof CompleteRollingReleaseRollingReleaseTarget> = z
    .nativeEnum(CompleteRollingReleaseRollingReleaseTarget);

/** @internal */
export const CompleteRollingReleaseCurrentDeployment$inboundSchema: z.ZodType<
  CompleteRollingReleaseCurrentDeployment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: types.number(),
  id: types.string(),
  name: types.string(),
  readyState: CompleteRollingReleaseRollingReleaseReadyState$inboundSchema,
  readyStateAt: types.optional(types.number()),
  source: types.optional(
    CompleteRollingReleaseRollingReleaseSource$inboundSchema,
  ),
  target: z.nullable(CompleteRollingReleaseRollingReleaseTarget$inboundSchema)
    .optional(),
  url: types.string(),
});

export function completeRollingReleaseCurrentDeploymentFromJSON(
  jsonString: string,
): SafeParseResult<
  CompleteRollingReleaseCurrentDeployment,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CompleteRollingReleaseCurrentDeployment$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CompleteRollingReleaseCurrentDeployment' from JSON`,
  );
}

/** @internal */
export const CompleteRollingReleaseNextStage$inboundSchema: z.ZodType<
  CompleteRollingReleaseNextStage,
  z.ZodTypeDef,
  unknown
> = z.object({
  duration: types.nullable(types.number()),
  index: types.number(),
  isFinalStage: types.boolean(),
  linearShift: types.optional(types.boolean()),
  requireApproval: types.boolean(),
  targetPercentage: types.number(),
});

export function completeRollingReleaseNextStageFromJSON(
  jsonString: string,
): SafeParseResult<CompleteRollingReleaseNextStage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompleteRollingReleaseNextStage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompleteRollingReleaseNextStage' from JSON`,
  );
}

/** @internal */
export const CompleteRollingReleaseStages$inboundSchema: z.ZodType<
  CompleteRollingReleaseStages,
  z.ZodTypeDef,
  unknown
> = z.object({
  duration: types.nullable(types.number()),
  index: types.number(),
  isFinalStage: types.boolean(),
  linearShift: types.optional(types.boolean()),
  requireApproval: types.boolean(),
  targetPercentage: types.number(),
});

export function completeRollingReleaseStagesFromJSON(
  jsonString: string,
): SafeParseResult<CompleteRollingReleaseStages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompleteRollingReleaseStages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompleteRollingReleaseStages' from JSON`,
  );
}

/** @internal */
export const CompleteRollingReleaseState$inboundSchema: z.ZodNativeEnum<
  typeof CompleteRollingReleaseState
> = z.nativeEnum(CompleteRollingReleaseState);

/** @internal */
export const CompleteRollingReleaseSubstate$inboundSchema: z.ZodNativeEnum<
  typeof CompleteRollingReleaseSubstate
> = z.nativeEnum(CompleteRollingReleaseSubstate);

/** @internal */
export const CompleteRollingReleaseRollingRelease$inboundSchema: z.ZodType<
  CompleteRollingReleaseRollingRelease,
  z.ZodTypeDef,
  unknown
> = z.object({
  activeStage: types.nullable(
    z.lazy(() => CompleteRollingReleaseActiveStage$inboundSchema),
  ),
  advancementType: CompleteRollingReleaseAdvancementType$inboundSchema,
  canaryDeployment: types.nullable(
    z.lazy(() => CompleteRollingReleaseCanaryDeployment$inboundSchema),
  ),
  currentCanaryPercentage: types.optional(types.number()),
  currentDeployment: types.nullable(
    z.lazy(() => CompleteRollingReleaseCurrentDeployment$inboundSchema),
  ),
  nextStage: types.nullable(
    z.lazy(() => CompleteRollingReleaseNextStage$inboundSchema),
  ),
  queuedDeploymentId: types.nullable(types.string()),
  stages: z.array(z.lazy(() => CompleteRollingReleaseStages$inboundSchema)),
  startedAt: types.number(),
  state: CompleteRollingReleaseState$inboundSchema,
  substate: types.nullable(CompleteRollingReleaseSubstate$inboundSchema),
  updatedAt: types.number(),
});

export function completeRollingReleaseRollingReleaseFromJSON(
  jsonString: string,
): SafeParseResult<CompleteRollingReleaseRollingRelease, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CompleteRollingReleaseRollingRelease$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompleteRollingReleaseRollingRelease' from JSON`,
  );
}

/** @internal */
export const CompleteRollingReleaseResponseBody$inboundSchema: z.ZodType<
  CompleteRollingReleaseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  rollingRelease: types.nullable(
    z.lazy(() => CompleteRollingReleaseRollingRelease$inboundSchema),
  ),
});

export function completeRollingReleaseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CompleteRollingReleaseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CompleteRollingReleaseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompleteRollingReleaseResponseBody' from JSON`,
  );
}
