/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import { VcrRepository, VcrRepository$inboundSchema } from "./vcrrepository.js";

export type CreateRepositoryRequestBody = {
  projectId: string;
  /**
   * Single Docker repository name component.
   */
  name: string;
};

export type CreateRepositoryRequest = {
  /**
   * The Team identifier to perform the request on behalf of.
   */
  teamId?: string | undefined;
  /**
   * The Team slug to perform the request on behalf of.
   */
  slug?: string | undefined;
  requestBody?: CreateRepositoryRequestBody | undefined;
};

export type CreateRepositoryResponseBody = {
  /**
   * A Vercel Container Registry repository.
   */
  repository: VcrRepository;
};

/** @internal */
export type CreateRepositoryRequestBody$Outbound = {
  projectId: string;
  name: string;
};

/** @internal */
export const CreateRepositoryRequestBody$outboundSchema: z.ZodType<
  CreateRepositoryRequestBody$Outbound,
  z.ZodTypeDef,
  CreateRepositoryRequestBody
> = z.object({
  projectId: z.string(),
  name: z.string(),
});

export function createRepositoryRequestBodyToJSON(
  createRepositoryRequestBody: CreateRepositoryRequestBody,
): string {
  return JSON.stringify(
    CreateRepositoryRequestBody$outboundSchema.parse(
      createRepositoryRequestBody,
    ),
  );
}

/** @internal */
export type CreateRepositoryRequest$Outbound = {
  teamId?: string | undefined;
  slug?: string | undefined;
  RequestBody?: CreateRepositoryRequestBody$Outbound | undefined;
};

/** @internal */
export const CreateRepositoryRequest$outboundSchema: z.ZodType<
  CreateRepositoryRequest$Outbound,
  z.ZodTypeDef,
  CreateRepositoryRequest
> = z.object({
  teamId: z.string().optional(),
  slug: z.string().optional(),
  requestBody: z.lazy(() => CreateRepositoryRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function createRepositoryRequestToJSON(
  createRepositoryRequest: CreateRepositoryRequest,
): string {
  return JSON.stringify(
    CreateRepositoryRequest$outboundSchema.parse(createRepositoryRequest),
  );
}

/** @internal */
export const CreateRepositoryResponseBody$inboundSchema: z.ZodType<
  CreateRepositoryResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  repository: VcrRepository$inboundSchema,
});

export function createRepositoryResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateRepositoryResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateRepositoryResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateRepositoryResponseBody' from JSON`,
  );
}
