/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type TypeOther = {
  type: string;
  additionalProperties?: { [k: string]: any } | undefined;
};

export const GetConnectorTokenSubjectConnectRequestType = {
  JwtBearer: "jwt-bearer",
} as const;
export type GetConnectorTokenSubjectConnectRequestType = ClosedEnum<
  typeof GetConnectorTokenSubjectConnectRequestType
>;

export type TypeJwtBearer = {
  type: GetConnectorTokenSubjectConnectRequestType;
  sub?: string | undefined;
  iss?: string | undefined;
  aud?: string | undefined;
  additionalClaims?: { [k: string]: any } | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export const GetConnectorTokenSubjectConnectType = {
  User: "user",
} as const;
export type GetConnectorTokenSubjectConnectType = ClosedEnum<
  typeof GetConnectorTokenSubjectConnectType
>;

export type TypeUser = {
  type: GetConnectorTokenSubjectConnectType;
  id?: string | undefined;
  issuer?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export const GetConnectorTokenSubjectType = {
  App: "app",
} as const;
export type GetConnectorTokenSubjectType = ClosedEnum<
  typeof GetConnectorTokenSubjectType
>;

export type TypeApp = {
  type: GetConnectorTokenSubjectType;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type Subject = TypeApp | TypeUser | TypeJwtBearer | TypeOther;

export type AuthorizationDetails = {
  type?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type GetConnectorTokenRequestBody = {
  subject?: TypeApp | TypeUser | TypeJwtBearer | TypeOther | undefined;
  installationId?: string | undefined;
  audience?: Array<string> | undefined;
  scopes?: Array<string> | undefined;
  resources?: Array<string> | undefined;
  authorizationDetails?: Array<AuthorizationDetails> | undefined;
  validityBufferMs?: number | undefined;
};

export type GetConnectorTokenRequest = {
  connector: string;
  requestBody?: GetConnectorTokenRequestBody | undefined;
};

export type Connector = {
  id: string;
  uid: string;
  type: string;
};

export type GetConnectorTokenResponseBody = {
  token: string;
  expiresAt: number;
  connector: Connector;
  name?: string | undefined;
  installationId?: string | undefined;
  tenantId?: string | undefined;
  externalSubject?: string | undefined;
  /**
   * Driver-specific metadata (e.g., botUserId for Slack).
   */
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const TypeOther$inboundSchema: z.ZodType<
  TypeOther,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    type: types.string(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type TypeOther$Outbound = {
  type: string;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const TypeOther$outboundSchema: z.ZodType<
  TypeOther$Outbound,
  z.ZodTypeDef,
  TypeOther
> = z.object({
  type: z.string(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function typeOtherToJSON(typeOther: TypeOther): string {
  return JSON.stringify(TypeOther$outboundSchema.parse(typeOther));
}
export function typeOtherFromJSON(
  jsonString: string,
): SafeParseResult<TypeOther, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypeOther$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypeOther' from JSON`,
  );
}

/** @internal */
export const GetConnectorTokenSubjectConnectRequestType$inboundSchema:
  z.ZodNativeEnum<typeof GetConnectorTokenSubjectConnectRequestType> = z
    .nativeEnum(GetConnectorTokenSubjectConnectRequestType);
/** @internal */
export const GetConnectorTokenSubjectConnectRequestType$outboundSchema:
  z.ZodNativeEnum<typeof GetConnectorTokenSubjectConnectRequestType> =
    GetConnectorTokenSubjectConnectRequestType$inboundSchema;

/** @internal */
export const TypeJwtBearer$inboundSchema: z.ZodType<
  TypeJwtBearer,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    type: GetConnectorTokenSubjectConnectRequestType$inboundSchema,
    sub: types.optional(types.string()),
    iss: types.optional(types.string()),
    aud: types.optional(types.string()),
    additionalClaims: types.optional(z.record(z.any())),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type TypeJwtBearer$Outbound = {
  type: string;
  sub?: string | undefined;
  iss?: string | undefined;
  aud?: string | undefined;
  additionalClaims?: { [k: string]: any } | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const TypeJwtBearer$outboundSchema: z.ZodType<
  TypeJwtBearer$Outbound,
  z.ZodTypeDef,
  TypeJwtBearer
> = z.object({
  type: GetConnectorTokenSubjectConnectRequestType$outboundSchema,
  sub: z.string().optional(),
  iss: z.string().optional(),
  aud: z.string().optional(),
  additionalClaims: z.record(z.any()).optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function typeJwtBearerToJSON(typeJwtBearer: TypeJwtBearer): string {
  return JSON.stringify(TypeJwtBearer$outboundSchema.parse(typeJwtBearer));
}
export function typeJwtBearerFromJSON(
  jsonString: string,
): SafeParseResult<TypeJwtBearer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypeJwtBearer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypeJwtBearer' from JSON`,
  );
}

/** @internal */
export const GetConnectorTokenSubjectConnectType$inboundSchema: z.ZodNativeEnum<
  typeof GetConnectorTokenSubjectConnectType
> = z.nativeEnum(GetConnectorTokenSubjectConnectType);
/** @internal */
export const GetConnectorTokenSubjectConnectType$outboundSchema:
  z.ZodNativeEnum<typeof GetConnectorTokenSubjectConnectType> =
    GetConnectorTokenSubjectConnectType$inboundSchema;

/** @internal */
export const TypeUser$inboundSchema: z.ZodType<
  TypeUser,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    type: GetConnectorTokenSubjectConnectType$inboundSchema,
    id: types.optional(types.string()),
    issuer: types.optional(types.string()),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type TypeUser$Outbound = {
  type: string;
  id?: string | undefined;
  issuer?: string | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const TypeUser$outboundSchema: z.ZodType<
  TypeUser$Outbound,
  z.ZodTypeDef,
  TypeUser
> = z.object({
  type: GetConnectorTokenSubjectConnectType$outboundSchema,
  id: z.string().optional(),
  issuer: z.string().optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function typeUserToJSON(typeUser: TypeUser): string {
  return JSON.stringify(TypeUser$outboundSchema.parse(typeUser));
}
export function typeUserFromJSON(
  jsonString: string,
): SafeParseResult<TypeUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypeUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypeUser' from JSON`,
  );
}

/** @internal */
export const GetConnectorTokenSubjectType$inboundSchema: z.ZodNativeEnum<
  typeof GetConnectorTokenSubjectType
> = z.nativeEnum(GetConnectorTokenSubjectType);
/** @internal */
export const GetConnectorTokenSubjectType$outboundSchema: z.ZodNativeEnum<
  typeof GetConnectorTokenSubjectType
> = GetConnectorTokenSubjectType$inboundSchema;

/** @internal */
export const TypeApp$inboundSchema: z.ZodType<TypeApp, z.ZodTypeDef, unknown> =
  collectExtraKeys$(
    z.object({
      type: GetConnectorTokenSubjectType$inboundSchema,
    }).catchall(z.any()),
    "additionalProperties",
    true,
  );
/** @internal */
export type TypeApp$Outbound = {
  type: string;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const TypeApp$outboundSchema: z.ZodType<
  TypeApp$Outbound,
  z.ZodTypeDef,
  TypeApp
> = z.object({
  type: GetConnectorTokenSubjectType$outboundSchema,
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function typeAppToJSON(typeApp: TypeApp): string {
  return JSON.stringify(TypeApp$outboundSchema.parse(typeApp));
}
export function typeAppFromJSON(
  jsonString: string,
): SafeParseResult<TypeApp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypeApp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypeApp' from JSON`,
  );
}

/** @internal */
export const Subject$inboundSchema: z.ZodType<Subject, z.ZodTypeDef, unknown> =
  smartUnion([
    z.lazy(() => TypeApp$inboundSchema),
    z.lazy(() => TypeUser$inboundSchema),
    z.lazy(() => TypeJwtBearer$inboundSchema),
    z.lazy(() => TypeOther$inboundSchema),
  ]);
/** @internal */
export type Subject$Outbound =
  | TypeApp$Outbound
  | TypeUser$Outbound
  | TypeJwtBearer$Outbound
  | TypeOther$Outbound;

/** @internal */
export const Subject$outboundSchema: z.ZodType<
  Subject$Outbound,
  z.ZodTypeDef,
  Subject
> = smartUnion([
  z.lazy(() => TypeApp$outboundSchema),
  z.lazy(() => TypeUser$outboundSchema),
  z.lazy(() => TypeJwtBearer$outboundSchema),
  z.lazy(() => TypeOther$outboundSchema),
]);

export function subjectToJSON(subject: Subject): string {
  return JSON.stringify(Subject$outboundSchema.parse(subject));
}
export function subjectFromJSON(
  jsonString: string,
): SafeParseResult<Subject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Subject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Subject' from JSON`,
  );
}

/** @internal */
export const AuthorizationDetails$inboundSchema: z.ZodType<
  AuthorizationDetails,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    type: types.optional(types.string()),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type AuthorizationDetails$Outbound = {
  type?: string | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const AuthorizationDetails$outboundSchema: z.ZodType<
  AuthorizationDetails$Outbound,
  z.ZodTypeDef,
  AuthorizationDetails
> = z.object({
  type: z.string().optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function authorizationDetailsToJSON(
  authorizationDetails: AuthorizationDetails,
): string {
  return JSON.stringify(
    AuthorizationDetails$outboundSchema.parse(authorizationDetails),
  );
}
export function authorizationDetailsFromJSON(
  jsonString: string,
): SafeParseResult<AuthorizationDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthorizationDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthorizationDetails' from JSON`,
  );
}

/** @internal */
export const GetConnectorTokenRequestBody$inboundSchema: z.ZodType<
  GetConnectorTokenRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  subject: types.optional(
    smartUnion([
      z.lazy(() => TypeApp$inboundSchema),
      z.lazy(() => TypeUser$inboundSchema),
      z.lazy(() => TypeJwtBearer$inboundSchema),
      z.lazy(() => TypeOther$inboundSchema),
    ]),
  ),
  installationId: types.optional(types.string()),
  audience: types.optional(z.array(types.string())),
  scopes: types.optional(z.array(types.string())),
  resources: types.optional(z.array(types.string())),
  authorizationDetails: types.optional(
    z.array(z.lazy(() => AuthorizationDetails$inboundSchema)),
  ),
  validityBufferMs: types.optional(types.number()),
});
/** @internal */
export type GetConnectorTokenRequestBody$Outbound = {
  subject?:
    | TypeApp$Outbound
    | TypeUser$Outbound
    | TypeJwtBearer$Outbound
    | TypeOther$Outbound
    | undefined;
  installationId?: string | undefined;
  audience?: Array<string> | undefined;
  scopes?: Array<string> | undefined;
  resources?: Array<string> | undefined;
  authorizationDetails?: Array<AuthorizationDetails$Outbound> | undefined;
  validityBufferMs?: number | undefined;
};

/** @internal */
export const GetConnectorTokenRequestBody$outboundSchema: z.ZodType<
  GetConnectorTokenRequestBody$Outbound,
  z.ZodTypeDef,
  GetConnectorTokenRequestBody
> = z.object({
  subject: smartUnion([
    z.lazy(() => TypeApp$outboundSchema),
    z.lazy(() => TypeUser$outboundSchema),
    z.lazy(() => TypeJwtBearer$outboundSchema),
    z.lazy(() => TypeOther$outboundSchema),
  ]).optional(),
  installationId: z.string().optional(),
  audience: z.array(z.string()).optional(),
  scopes: z.array(z.string()).optional(),
  resources: z.array(z.string()).optional(),
  authorizationDetails: z.array(
    z.lazy(() => AuthorizationDetails$outboundSchema),
  ).optional(),
  validityBufferMs: z.number().optional(),
});

export function getConnectorTokenRequestBodyToJSON(
  getConnectorTokenRequestBody: GetConnectorTokenRequestBody,
): string {
  return JSON.stringify(
    GetConnectorTokenRequestBody$outboundSchema.parse(
      getConnectorTokenRequestBody,
    ),
  );
}
export function getConnectorTokenRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetConnectorTokenRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetConnectorTokenRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetConnectorTokenRequestBody' from JSON`,
  );
}

/** @internal */
export const GetConnectorTokenRequest$inboundSchema: z.ZodType<
  GetConnectorTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  connector: types.string(),
  RequestBody: types.optional(
    z.lazy(() => GetConnectorTokenRequestBody$inboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type GetConnectorTokenRequest$Outbound = {
  connector: string;
  RequestBody?: GetConnectorTokenRequestBody$Outbound | undefined;
};

/** @internal */
export const GetConnectorTokenRequest$outboundSchema: z.ZodType<
  GetConnectorTokenRequest$Outbound,
  z.ZodTypeDef,
  GetConnectorTokenRequest
> = z.object({
  connector: z.string(),
  requestBody: z.lazy(() => GetConnectorTokenRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function getConnectorTokenRequestToJSON(
  getConnectorTokenRequest: GetConnectorTokenRequest,
): string {
  return JSON.stringify(
    GetConnectorTokenRequest$outboundSchema.parse(getConnectorTokenRequest),
  );
}
export function getConnectorTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetConnectorTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetConnectorTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetConnectorTokenRequest' from JSON`,
  );
}

/** @internal */
export const Connector$inboundSchema: z.ZodType<
  Connector,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.string(),
  uid: types.string(),
  type: types.string(),
});
/** @internal */
export type Connector$Outbound = {
  id: string;
  uid: string;
  type: string;
};

/** @internal */
export const Connector$outboundSchema: z.ZodType<
  Connector$Outbound,
  z.ZodTypeDef,
  Connector
> = z.object({
  id: z.string(),
  uid: z.string(),
  type: z.string(),
});

export function connectorToJSON(connector: Connector): string {
  return JSON.stringify(Connector$outboundSchema.parse(connector));
}
export function connectorFromJSON(
  jsonString: string,
): SafeParseResult<Connector, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Connector$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Connector' from JSON`,
  );
}

/** @internal */
export const GetConnectorTokenResponseBody$inboundSchema: z.ZodType<
  GetConnectorTokenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: types.string(),
  expiresAt: types.number(),
  connector: z.lazy(() => Connector$inboundSchema),
  name: types.optional(types.string()),
  installationId: types.optional(types.string()),
  tenantId: types.optional(types.string()),
  externalSubject: types.optional(types.string()),
  metadata: types.optional(z.record(z.any())),
});
/** @internal */
export type GetConnectorTokenResponseBody$Outbound = {
  token: string;
  expiresAt: number;
  connector: Connector$Outbound;
  name?: string | undefined;
  installationId?: string | undefined;
  tenantId?: string | undefined;
  externalSubject?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const GetConnectorTokenResponseBody$outboundSchema: z.ZodType<
  GetConnectorTokenResponseBody$Outbound,
  z.ZodTypeDef,
  GetConnectorTokenResponseBody
> = z.object({
  token: z.string(),
  expiresAt: z.number(),
  connector: z.lazy(() => Connector$outboundSchema),
  name: z.string().optional(),
  installationId: z.string().optional(),
  tenantId: z.string().optional(),
  externalSubject: z.string().optional(),
  metadata: z.record(z.any()).optional(),
});

export function getConnectorTokenResponseBodyToJSON(
  getConnectorTokenResponseBody: GetConnectorTokenResponseBody,
): string {
  return JSON.stringify(
    GetConnectorTokenResponseBody$outboundSchema.parse(
      getConnectorTokenResponseBody,
    ),
  );
}
export function getConnectorTokenResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetConnectorTokenResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetConnectorTokenResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetConnectorTokenResponseBody' from JSON`,
  );
}
