/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  Snapshot,
  Snapshot$inboundSchema,
  Snapshot$Outbound,
  Snapshot$outboundSchema,
} from "./snapshot.js";

export type GetSnapshotRequest = {
  /**
   * The unique identifier of the snapshot to retrieve.
   */
  snapshotId: string;
  /**
   * The Team identifier to perform the request on behalf of.
   */
  teamId?: string | undefined;
  /**
   * The Team slug to perform the request on behalf of.
   */
  slug?: string | undefined;
};

export type GetSnapshotResponseBody = {
  /**
   * This object contains information related to a Snapshot of a Vercel Sandbox.
   */
  snapshot: Snapshot;
};

/** @internal */
export const GetSnapshotRequest$inboundSchema: z.ZodType<
  GetSnapshotRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  snapshotId: types.string(),
  teamId: types.optional(types.string()),
  slug: types.optional(types.string()),
});
/** @internal */
export type GetSnapshotRequest$Outbound = {
  snapshotId: string;
  teamId?: string | undefined;
  slug?: string | undefined;
};

/** @internal */
export const GetSnapshotRequest$outboundSchema: z.ZodType<
  GetSnapshotRequest$Outbound,
  z.ZodTypeDef,
  GetSnapshotRequest
> = z.object({
  snapshotId: z.string(),
  teamId: z.string().optional(),
  slug: z.string().optional(),
});

export function getSnapshotRequestToJSON(
  getSnapshotRequest: GetSnapshotRequest,
): string {
  return JSON.stringify(
    GetSnapshotRequest$outboundSchema.parse(getSnapshotRequest),
  );
}
export function getSnapshotRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSnapshotRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSnapshotRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSnapshotRequest' from JSON`,
  );
}

/** @internal */
export const GetSnapshotResponseBody$inboundSchema: z.ZodType<
  GetSnapshotResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  snapshot: Snapshot$inboundSchema,
});
/** @internal */
export type GetSnapshotResponseBody$Outbound = {
  snapshot: Snapshot$Outbound;
};

/** @internal */
export const GetSnapshotResponseBody$outboundSchema: z.ZodType<
  GetSnapshotResponseBody$Outbound,
  z.ZodTypeDef,
  GetSnapshotResponseBody
> = z.object({
  snapshot: Snapshot$outboundSchema,
});

export function getSnapshotResponseBodyToJSON(
  getSnapshotResponseBody: GetSnapshotResponseBody,
): string {
  return JSON.stringify(
    GetSnapshotResponseBody$outboundSchema.parse(getSnapshotResponseBody),
  );
}
export function getSnapshotResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetSnapshotResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSnapshotResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSnapshotResponseBody' from JSON`,
  );
}
