/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetV1SecurityFirewallEventsRequest = {
  projectId: string;
  startTimestamp?: number | undefined;
  endTimestamp?: number | undefined;
  hosts?: string | undefined;
};

export type GetV1SecurityFirewallEventsActions = {
  startTime: string;
  endTime: string;
  isActive: boolean;
  actionType: string;
  host: string;
  publicIp: string;
  count: number;
};

export type GetV1SecurityFirewallEventsResponseBody = {
  actions: Array<GetV1SecurityFirewallEventsActions>;
};

/** @internal */
export const GetV1SecurityFirewallEventsRequest$inboundSchema: z.ZodType<
  GetV1SecurityFirewallEventsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectId: types.string(),
  startTimestamp: types.optional(types.number()),
  endTimestamp: types.optional(types.number()),
  hosts: types.optional(types.string()),
});
/** @internal */
export type GetV1SecurityFirewallEventsRequest$Outbound = {
  projectId: string;
  startTimestamp?: number | undefined;
  endTimestamp?: number | undefined;
  hosts?: string | undefined;
};

/** @internal */
export const GetV1SecurityFirewallEventsRequest$outboundSchema: z.ZodType<
  GetV1SecurityFirewallEventsRequest$Outbound,
  z.ZodTypeDef,
  GetV1SecurityFirewallEventsRequest
> = z.object({
  projectId: z.string(),
  startTimestamp: z.number().optional(),
  endTimestamp: z.number().optional(),
  hosts: z.string().optional(),
});

export function getV1SecurityFirewallEventsRequestToJSON(
  getV1SecurityFirewallEventsRequest: GetV1SecurityFirewallEventsRequest,
): string {
  return JSON.stringify(
    GetV1SecurityFirewallEventsRequest$outboundSchema.parse(
      getV1SecurityFirewallEventsRequest,
    ),
  );
}
export function getV1SecurityFirewallEventsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SecurityFirewallEventsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1SecurityFirewallEventsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SecurityFirewallEventsRequest' from JSON`,
  );
}

/** @internal */
export const GetV1SecurityFirewallEventsActions$inboundSchema: z.ZodType<
  GetV1SecurityFirewallEventsActions,
  z.ZodTypeDef,
  unknown
> = z.object({
  startTime: types.string(),
  endTime: types.string(),
  isActive: types.boolean(),
  action_type: types.string(),
  host: types.string(),
  public_ip: types.string(),
  count: types.number(),
}).transform((v) => {
  return remap$(v, {
    "action_type": "actionType",
    "public_ip": "publicIp",
  });
});
/** @internal */
export type GetV1SecurityFirewallEventsActions$Outbound = {
  startTime: string;
  endTime: string;
  isActive: boolean;
  action_type: string;
  host: string;
  public_ip: string;
  count: number;
};

/** @internal */
export const GetV1SecurityFirewallEventsActions$outboundSchema: z.ZodType<
  GetV1SecurityFirewallEventsActions$Outbound,
  z.ZodTypeDef,
  GetV1SecurityFirewallEventsActions
> = z.object({
  startTime: z.string(),
  endTime: z.string(),
  isActive: z.boolean(),
  actionType: z.string(),
  host: z.string(),
  publicIp: z.string(),
  count: z.number(),
}).transform((v) => {
  return remap$(v, {
    actionType: "action_type",
    publicIp: "public_ip",
  });
});

export function getV1SecurityFirewallEventsActionsToJSON(
  getV1SecurityFirewallEventsActions: GetV1SecurityFirewallEventsActions,
): string {
  return JSON.stringify(
    GetV1SecurityFirewallEventsActions$outboundSchema.parse(
      getV1SecurityFirewallEventsActions,
    ),
  );
}
export function getV1SecurityFirewallEventsActionsFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SecurityFirewallEventsActions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1SecurityFirewallEventsActions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SecurityFirewallEventsActions' from JSON`,
  );
}

/** @internal */
export const GetV1SecurityFirewallEventsResponseBody$inboundSchema: z.ZodType<
  GetV1SecurityFirewallEventsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  actions: z.array(
    z.lazy(() => GetV1SecurityFirewallEventsActions$inboundSchema),
  ),
});
/** @internal */
export type GetV1SecurityFirewallEventsResponseBody$Outbound = {
  actions: Array<GetV1SecurityFirewallEventsActions$Outbound>;
};

/** @internal */
export const GetV1SecurityFirewallEventsResponseBody$outboundSchema: z.ZodType<
  GetV1SecurityFirewallEventsResponseBody$Outbound,
  z.ZodTypeDef,
  GetV1SecurityFirewallEventsResponseBody
> = z.object({
  actions: z.array(
    z.lazy(() => GetV1SecurityFirewallEventsActions$outboundSchema),
  ),
});

export function getV1SecurityFirewallEventsResponseBodyToJSON(
  getV1SecurityFirewallEventsResponseBody:
    GetV1SecurityFirewallEventsResponseBody,
): string {
  return JSON.stringify(
    GetV1SecurityFirewallEventsResponseBody$outboundSchema.parse(
      getV1SecurityFirewallEventsResponseBody,
    ),
  );
}
export function getV1SecurityFirewallEventsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1SecurityFirewallEventsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1SecurityFirewallEventsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1SecurityFirewallEventsResponseBody' from JSON`,
  );
}
