/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UserEvent,
  UserEvent$inboundSchema,
  UserEvent$Outbound,
  UserEvent$outboundSchema,
} from "./userevent.js";

export type ListUserEventsRequest = {
  /**
   * Maximum number of items which may be returned.
   */
  limit?: number | undefined;
  /**
   * Timestamp to only include items created since then.
   */
  since?: string | undefined;
  /**
   * Timestamp to only include items created until then.
   */
  until?: string | undefined;
  /**
   * Comma-delimited list of event \"types\" to filter the results by.
   */
  types?: string | undefined;
  /**
   * Deprecated. Use `principalId` instead. If `principalId` and `userId` both exist, `principalId` will be used.
   */
  userId?: string | undefined;
  /**
   * When retrieving events for a Team, the `principalId` parameter may be specified to filter events generated by a specific principal.
   */
  principalId?: string | undefined;
  /**
   * Comma-delimited list of project IDs to filter the results by.
   */
  projectIds?: string | undefined;
  /**
   * When set to `true`, the response will include the `payload` field for each event.
   */
  withPayload?: string | undefined;
  /**
   * The Team identifier to perform the request on behalf of.
   */
  teamId?: string | undefined;
  /**
   * The Team slug to perform the request on behalf of.
   */
  slug?: string | undefined;
};

/**
 * Successful response.
 */
export type ListUserEventsResponseBody2 = {
  /**
   * Array of events generated by the User.
   */
  events: Array<UserEvent>;
};

export type ListUserEventsResponseBody1 = {};

/**
 * Successful response.
 */
export type ListUserEventsResponseBody =
  | ListUserEventsResponseBody2
  | ListUserEventsResponseBody1;

/** @internal */
export const ListUserEventsRequest$inboundSchema: z.ZodType<
  ListUserEventsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: types.optional(types.number()),
  since: types.optional(types.string()),
  until: types.optional(types.string()),
  types: types.optional(types.string()),
  userId: types.optional(types.string()),
  principalId: types.optional(types.string()),
  projectIds: types.optional(types.string()),
  withPayload: types.optional(types.string()),
  teamId: types.optional(types.string()),
  slug: types.optional(types.string()),
});
/** @internal */
export type ListUserEventsRequest$Outbound = {
  limit?: number | undefined;
  since?: string | undefined;
  until?: string | undefined;
  types?: string | undefined;
  userId?: string | undefined;
  principalId?: string | undefined;
  projectIds?: string | undefined;
  withPayload?: string | undefined;
  teamId?: string | undefined;
  slug?: string | undefined;
};

/** @internal */
export const ListUserEventsRequest$outboundSchema: z.ZodType<
  ListUserEventsRequest$Outbound,
  z.ZodTypeDef,
  ListUserEventsRequest
> = z.object({
  limit: z.number().optional(),
  since: z.string().optional(),
  until: z.string().optional(),
  types: z.string().optional(),
  userId: z.string().optional(),
  principalId: z.string().optional(),
  projectIds: z.string().optional(),
  withPayload: z.string().optional(),
  teamId: z.string().optional(),
  slug: z.string().optional(),
});

export function listUserEventsRequestToJSON(
  listUserEventsRequest: ListUserEventsRequest,
): string {
  return JSON.stringify(
    ListUserEventsRequest$outboundSchema.parse(listUserEventsRequest),
  );
}
export function listUserEventsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListUserEventsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUserEventsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUserEventsRequest' from JSON`,
  );
}

/** @internal */
export const ListUserEventsResponseBody2$inboundSchema: z.ZodType<
  ListUserEventsResponseBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  events: z.array(UserEvent$inboundSchema),
});
/** @internal */
export type ListUserEventsResponseBody2$Outbound = {
  events: Array<UserEvent$Outbound>;
};

/** @internal */
export const ListUserEventsResponseBody2$outboundSchema: z.ZodType<
  ListUserEventsResponseBody2$Outbound,
  z.ZodTypeDef,
  ListUserEventsResponseBody2
> = z.object({
  events: z.array(UserEvent$outboundSchema),
});

export function listUserEventsResponseBody2ToJSON(
  listUserEventsResponseBody2: ListUserEventsResponseBody2,
): string {
  return JSON.stringify(
    ListUserEventsResponseBody2$outboundSchema.parse(
      listUserEventsResponseBody2,
    ),
  );
}
export function listUserEventsResponseBody2FromJSON(
  jsonString: string,
): SafeParseResult<ListUserEventsResponseBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUserEventsResponseBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUserEventsResponseBody2' from JSON`,
  );
}

/** @internal */
export const ListUserEventsResponseBody1$inboundSchema: z.ZodType<
  ListUserEventsResponseBody1,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type ListUserEventsResponseBody1$Outbound = {};

/** @internal */
export const ListUserEventsResponseBody1$outboundSchema: z.ZodType<
  ListUserEventsResponseBody1$Outbound,
  z.ZodTypeDef,
  ListUserEventsResponseBody1
> = z.object({});

export function listUserEventsResponseBody1ToJSON(
  listUserEventsResponseBody1: ListUserEventsResponseBody1,
): string {
  return JSON.stringify(
    ListUserEventsResponseBody1$outboundSchema.parse(
      listUserEventsResponseBody1,
    ),
  );
}
export function listUserEventsResponseBody1FromJSON(
  jsonString: string,
): SafeParseResult<ListUserEventsResponseBody1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUserEventsResponseBody1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUserEventsResponseBody1' from JSON`,
  );
}

/** @internal */
export const ListUserEventsResponseBody$inboundSchema: z.ZodType<
  ListUserEventsResponseBody,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  z.lazy(() => ListUserEventsResponseBody2$inboundSchema),
  z.lazy(() => ListUserEventsResponseBody1$inboundSchema),
]);
/** @internal */
export type ListUserEventsResponseBody$Outbound =
  | ListUserEventsResponseBody2$Outbound
  | ListUserEventsResponseBody1$Outbound;

/** @internal */
export const ListUserEventsResponseBody$outboundSchema: z.ZodType<
  ListUserEventsResponseBody$Outbound,
  z.ZodTypeDef,
  ListUserEventsResponseBody
> = smartUnion([
  z.lazy(() => ListUserEventsResponseBody2$outboundSchema),
  z.lazy(() => ListUserEventsResponseBody1$outboundSchema),
]);

export function listUserEventsResponseBodyToJSON(
  listUserEventsResponseBody: ListUserEventsResponseBody,
): string {
  return JSON.stringify(
    ListUserEventsResponseBody$outboundSchema.parse(listUserEventsResponseBody),
  );
}
export function listUserEventsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListUserEventsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUserEventsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUserEventsResponseBody' from JSON`,
  );
}
