/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type StatusCode = number | string;

export type Redirects = {
  source: string;
  destination: string;
  statusCode?: number | string | undefined;
  permanent?: boolean | undefined;
  caseSensitive?: boolean | undefined;
  query?: boolean | undefined;
};

export type PutV1BulkRedirectsRequestBody = {
  projectId: string;
  teamId: string;
  overwrite?: boolean | undefined;
  name?: string | undefined;
  redirects?: Array<Redirects> | undefined;
};

export type PutV1BulkRedirectsVersion = {
  /**
   * The unique identifier for the version.
   */
  id: string;
  /**
   * The key of the version. The key may be duplicated across versions if the contents are the same as a different version.
   */
  key: string;
  lastModified: number;
  createdBy: string;
  /**
   * Optional name for the version. If not provided, defaults to an ISO timestamp string.
   */
  name?: string | undefined;
  /**
   * Whether this version has not been promoted to production yet and is not serving end users.
   */
  isStaging?: boolean | undefined;
  /**
   * Whether this version is currently live in production.
   */
  isLive?: boolean | undefined;
  /**
   * The number of redirects in this version.
   */
  redirectCount?: number | undefined;
  /**
   * The staging link for previewing redirects in this version.
   */
  alias?: string | undefined;
};

export type PutV1BulkRedirectsResponseBody = {
  alias: string | null;
  version: PutV1BulkRedirectsVersion;
};

/** @internal */
export const StatusCode$inboundSchema: z.ZodType<
  StatusCode,
  z.ZodTypeDef,
  unknown
> = z.union([z.number(), z.string()]);
/** @internal */
export type StatusCode$Outbound = number | string;

/** @internal */
export const StatusCode$outboundSchema: z.ZodType<
  StatusCode$Outbound,
  z.ZodTypeDef,
  StatusCode
> = z.union([z.number(), z.string()]);

export function statusCodeToJSON(statusCode: StatusCode): string {
  return JSON.stringify(StatusCode$outboundSchema.parse(statusCode));
}
export function statusCodeFromJSON(
  jsonString: string,
): SafeParseResult<StatusCode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusCode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusCode' from JSON`,
  );
}

/** @internal */
export const Redirects$inboundSchema: z.ZodType<
  Redirects,
  z.ZodTypeDef,
  unknown
> = z.object({
  source: z.string(),
  destination: z.string(),
  statusCode: z.union([z.number(), z.string()]).optional(),
  permanent: z.boolean().optional(),
  caseSensitive: z.boolean().optional(),
  query: z.boolean().optional(),
});
/** @internal */
export type Redirects$Outbound = {
  source: string;
  destination: string;
  statusCode?: number | string | undefined;
  permanent?: boolean | undefined;
  caseSensitive?: boolean | undefined;
  query?: boolean | undefined;
};

/** @internal */
export const Redirects$outboundSchema: z.ZodType<
  Redirects$Outbound,
  z.ZodTypeDef,
  Redirects
> = z.object({
  source: z.string(),
  destination: z.string(),
  statusCode: z.union([z.number(), z.string()]).optional(),
  permanent: z.boolean().optional(),
  caseSensitive: z.boolean().optional(),
  query: z.boolean().optional(),
});

export function redirectsToJSON(redirects: Redirects): string {
  return JSON.stringify(Redirects$outboundSchema.parse(redirects));
}
export function redirectsFromJSON(
  jsonString: string,
): SafeParseResult<Redirects, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Redirects$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Redirects' from JSON`,
  );
}

/** @internal */
export const PutV1BulkRedirectsRequestBody$inboundSchema: z.ZodType<
  PutV1BulkRedirectsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectId: z.string(),
  teamId: z.string(),
  overwrite: z.boolean().optional(),
  name: z.string().optional(),
  redirects: z.array(z.lazy(() => Redirects$inboundSchema)).optional(),
});
/** @internal */
export type PutV1BulkRedirectsRequestBody$Outbound = {
  projectId: string;
  teamId: string;
  overwrite?: boolean | undefined;
  name?: string | undefined;
  redirects?: Array<Redirects$Outbound> | undefined;
};

/** @internal */
export const PutV1BulkRedirectsRequestBody$outboundSchema: z.ZodType<
  PutV1BulkRedirectsRequestBody$Outbound,
  z.ZodTypeDef,
  PutV1BulkRedirectsRequestBody
> = z.object({
  projectId: z.string(),
  teamId: z.string(),
  overwrite: z.boolean().optional(),
  name: z.string().optional(),
  redirects: z.array(z.lazy(() => Redirects$outboundSchema)).optional(),
});

export function putV1BulkRedirectsRequestBodyToJSON(
  putV1BulkRedirectsRequestBody: PutV1BulkRedirectsRequestBody,
): string {
  return JSON.stringify(
    PutV1BulkRedirectsRequestBody$outboundSchema.parse(
      putV1BulkRedirectsRequestBody,
    ),
  );
}
export function putV1BulkRedirectsRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PutV1BulkRedirectsRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV1BulkRedirectsRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV1BulkRedirectsRequestBody' from JSON`,
  );
}

/** @internal */
export const PutV1BulkRedirectsVersion$inboundSchema: z.ZodType<
  PutV1BulkRedirectsVersion,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  key: z.string(),
  lastModified: z.number(),
  createdBy: z.string(),
  name: z.string().optional(),
  isStaging: z.boolean().optional(),
  isLive: z.boolean().optional(),
  redirectCount: z.number().optional(),
  alias: z.string().optional(),
});
/** @internal */
export type PutV1BulkRedirectsVersion$Outbound = {
  id: string;
  key: string;
  lastModified: number;
  createdBy: string;
  name?: string | undefined;
  isStaging?: boolean | undefined;
  isLive?: boolean | undefined;
  redirectCount?: number | undefined;
  alias?: string | undefined;
};

/** @internal */
export const PutV1BulkRedirectsVersion$outboundSchema: z.ZodType<
  PutV1BulkRedirectsVersion$Outbound,
  z.ZodTypeDef,
  PutV1BulkRedirectsVersion
> = z.object({
  id: z.string(),
  key: z.string(),
  lastModified: z.number(),
  createdBy: z.string(),
  name: z.string().optional(),
  isStaging: z.boolean().optional(),
  isLive: z.boolean().optional(),
  redirectCount: z.number().optional(),
  alias: z.string().optional(),
});

export function putV1BulkRedirectsVersionToJSON(
  putV1BulkRedirectsVersion: PutV1BulkRedirectsVersion,
): string {
  return JSON.stringify(
    PutV1BulkRedirectsVersion$outboundSchema.parse(putV1BulkRedirectsVersion),
  );
}
export function putV1BulkRedirectsVersionFromJSON(
  jsonString: string,
): SafeParseResult<PutV1BulkRedirectsVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV1BulkRedirectsVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV1BulkRedirectsVersion' from JSON`,
  );
}

/** @internal */
export const PutV1BulkRedirectsResponseBody$inboundSchema: z.ZodType<
  PutV1BulkRedirectsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  alias: z.nullable(z.string()),
  version: z.lazy(() => PutV1BulkRedirectsVersion$inboundSchema),
});
/** @internal */
export type PutV1BulkRedirectsResponseBody$Outbound = {
  alias: string | null;
  version: PutV1BulkRedirectsVersion$Outbound;
};

/** @internal */
export const PutV1BulkRedirectsResponseBody$outboundSchema: z.ZodType<
  PutV1BulkRedirectsResponseBody$Outbound,
  z.ZodTypeDef,
  PutV1BulkRedirectsResponseBody
> = z.object({
  alias: z.nullable(z.string()),
  version: z.lazy(() => PutV1BulkRedirectsVersion$outboundSchema),
});

export function putV1BulkRedirectsResponseBodyToJSON(
  putV1BulkRedirectsResponseBody: PutV1BulkRedirectsResponseBody,
): string {
  return JSON.stringify(
    PutV1BulkRedirectsResponseBody$outboundSchema.parse(
      putV1BulkRedirectsResponseBody,
    ),
  );
}
export function putV1BulkRedirectsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PutV1BulkRedirectsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV1BulkRedirectsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV1BulkRedirectsResponseBody' from JSON`,
  );
}
