/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type StatusRequest = {
  /**
   * The Team identifier to perform the request on behalf of.
   */
  teamId?: string | undefined;
  /**
   * The Team slug to perform the request on behalf of.
   */
  slug?: string | undefined;
};

export const ResponseBodyStatus = {
  Disabled: "disabled",
  Enabled: "enabled",
  OverLimit: "over_limit",
  Paused: "paused",
} as const;
export type ResponseBodyStatus = ClosedEnum<typeof ResponseBodyStatus>;

export type ResponseBody2 = {
  status: ResponseBodyStatus;
};

export type ResponseBody1 = {
  status: string;
};

export type StatusResponseBody = ResponseBody1 | ResponseBody2;

/** @internal */
export const StatusRequest$inboundSchema: z.ZodType<
  StatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  teamId: types.optional(types.string()),
  slug: types.optional(types.string()),
});
/** @internal */
export type StatusRequest$Outbound = {
  teamId?: string | undefined;
  slug?: string | undefined;
};

/** @internal */
export const StatusRequest$outboundSchema: z.ZodType<
  StatusRequest$Outbound,
  z.ZodTypeDef,
  StatusRequest
> = z.object({
  teamId: z.string().optional(),
  slug: z.string().optional(),
});

export function statusRequestToJSON(statusRequest: StatusRequest): string {
  return JSON.stringify(StatusRequest$outboundSchema.parse(statusRequest));
}
export function statusRequestFromJSON(
  jsonString: string,
): SafeParseResult<StatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusRequest' from JSON`,
  );
}

/** @internal */
export const ResponseBodyStatus$inboundSchema: z.ZodNativeEnum<
  typeof ResponseBodyStatus
> = z.nativeEnum(ResponseBodyStatus);
/** @internal */
export const ResponseBodyStatus$outboundSchema: z.ZodNativeEnum<
  typeof ResponseBodyStatus
> = ResponseBodyStatus$inboundSchema;

/** @internal */
export const ResponseBody2$inboundSchema: z.ZodType<
  ResponseBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: ResponseBodyStatus$inboundSchema,
});
/** @internal */
export type ResponseBody2$Outbound = {
  status: string;
};

/** @internal */
export const ResponseBody2$outboundSchema: z.ZodType<
  ResponseBody2$Outbound,
  z.ZodTypeDef,
  ResponseBody2
> = z.object({
  status: ResponseBodyStatus$outboundSchema,
});

export function responseBody2ToJSON(responseBody2: ResponseBody2): string {
  return JSON.stringify(ResponseBody2$outboundSchema.parse(responseBody2));
}
export function responseBody2FromJSON(
  jsonString: string,
): SafeParseResult<ResponseBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseBody2' from JSON`,
  );
}

/** @internal */
export const ResponseBody1$inboundSchema: z.ZodType<
  ResponseBody1,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: types.string(),
});
/** @internal */
export type ResponseBody1$Outbound = {
  status: string;
};

/** @internal */
export const ResponseBody1$outboundSchema: z.ZodType<
  ResponseBody1$Outbound,
  z.ZodTypeDef,
  ResponseBody1
> = z.object({
  status: z.string(),
});

export function responseBody1ToJSON(responseBody1: ResponseBody1): string {
  return JSON.stringify(ResponseBody1$outboundSchema.parse(responseBody1));
}
export function responseBody1FromJSON(
  jsonString: string,
): SafeParseResult<ResponseBody1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseBody1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseBody1' from JSON`,
  );
}

/** @internal */
export const StatusResponseBody$inboundSchema: z.ZodType<
  StatusResponseBody,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  z.lazy(() => ResponseBody1$inboundSchema),
  z.lazy(() => ResponseBody2$inboundSchema),
]);
/** @internal */
export type StatusResponseBody$Outbound =
  | ResponseBody1$Outbound
  | ResponseBody2$Outbound;

/** @internal */
export const StatusResponseBody$outboundSchema: z.ZodType<
  StatusResponseBody$Outbound,
  z.ZodTypeDef,
  StatusResponseBody
> = smartUnion([
  z.lazy(() => ResponseBody1$outboundSchema),
  z.lazy(() => ResponseBody2$outboundSchema),
]);

export function statusResponseBodyToJSON(
  statusResponseBody: StatusResponseBody,
): string {
  return JSON.stringify(
    StatusResponseBody$outboundSchema.parse(statusResponseBody),
  );
}
export function statusResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<StatusResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusResponseBody' from JSON`,
  );
}
