/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ConnectUpdateConnectorRequest,
  ConnectUpdateConnectorRequest$Outbound,
  ConnectUpdateConnectorRequest$outboundSchema,
} from "./connectupdateconnectorrequest.js";

export type UpdateConnectorRequest = {
  /**
   * Stable connector ID or URL-encoded team-scoped UID. Examples: `scl_abc123` or `slack%2Fmy-bot`.
   */
  connector: string;
  /**
   * The team ID that scopes the request. Do not send it with slug. If both are omitted, Vercel uses the team associated with the token or the authenticated user's default team. The request returns 401 if no team can be selected.
   */
  teamId?: string | undefined;
  /**
   * The team slug that scopes the request. Do not send it with teamId. If both are omitted, Vercel uses the team associated with the token or the authenticated user's default team. The request returns 401 if no team can be selected.
   */
  slug?: string | undefined;
  connectUpdateConnectorRequest: ConnectUpdateConnectorRequest;
};

/** @internal */
export type UpdateConnectorRequest$Outbound = {
  connector: string;
  teamId?: string | undefined;
  slug?: string | undefined;
  ConnectUpdateConnectorRequest: ConnectUpdateConnectorRequest$Outbound;
};

/** @internal */
export const UpdateConnectorRequest$outboundSchema: z.ZodType<
  UpdateConnectorRequest$Outbound,
  z.ZodTypeDef,
  UpdateConnectorRequest
> = z.object({
  connector: z.string(),
  teamId: z.string().optional(),
  slug: z.string().optional(),
  connectUpdateConnectorRequest: ConnectUpdateConnectorRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    connectUpdateConnectorRequest: "ConnectUpdateConnectorRequest",
  });
});

export function updateConnectorRequestToJSON(
  updateConnectorRequest: UpdateConnectorRequest,
): string {
  return JSON.stringify(
    UpdateConnectorRequest$outboundSchema.parse(updateConnectorRequest),
  );
}
