/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type UploadFileRequest = {
  /**
   * The file size in bytes
   */
  contentLength?: number | undefined;
  /**
   * The file SHA1 used to check the integrity
   */
  xVercelDigest?: string | undefined;
  /**
   * The file SHA1 used to check the integrity
   */
  xNowDigest?: string | undefined;
  /**
   * The file size as an alternative to `Content-Length`
   */
  xNowSize?: number | undefined;
  /**
   * The Team identifier to perform the request on behalf of.
   */
  teamId?: string | undefined;
  /**
   * The Team slug to perform the request on behalf of.
   */
  slug?: string | undefined;
  requestBody?:
    | ReadableStream<Uint8Array>
    | Blob
    | ArrayBuffer
    | Uint8Array
    | undefined;
};

export type UploadFileResponseBody2 = {};

export type UploadFileResponseBody1 = {
  /**
   * Array of URLs where the file was updated
   */
  urls: Array<string>;
};

/**
 * File already uploaded
 *
 * @remarks
 * File successfully uploaded
 */
export type UploadFileResponseBody =
  | UploadFileResponseBody1
  | UploadFileResponseBody2;

/** @internal */
export type UploadFileRequest$Outbound = {
  "'content-Length'"?: number | undefined;
  "'x-Vercel-Digest'"?: string | undefined;
  "'x-Now-Digest'"?: string | undefined;
  "'x-Now-Size'"?: number | undefined;
  teamId?: string | undefined;
  slug?: string | undefined;
  RequestBody?:
    | ReadableStream<Uint8Array>
    | Blob
    | ArrayBuffer
    | Uint8Array
    | undefined;
};

/** @internal */
export const UploadFileRequest$outboundSchema: z.ZodType<
  UploadFileRequest$Outbound,
  z.ZodTypeDef,
  UploadFileRequest
> = z.object({
  contentLength: z.number().optional(),
  xVercelDigest: z.string().optional(),
  xNowDigest: z.string().optional(),
  xNowSize: z.number().optional(),
  teamId: z.string().optional(),
  slug: z.string().optional(),
  requestBody: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]).optional(),
}).transform((v) => {
  return remap$(v, {
    contentLength: "'content-Length'",
    xVercelDigest: "'x-Vercel-Digest'",
    xNowDigest: "'x-Now-Digest'",
    xNowSize: "'x-Now-Size'",
    requestBody: "RequestBody",
  });
});

export function uploadFileRequestToJSON(
  uploadFileRequest: UploadFileRequest,
): string {
  return JSON.stringify(
    UploadFileRequest$outboundSchema.parse(uploadFileRequest),
  );
}

/** @internal */
export const UploadFileResponseBody2$inboundSchema: z.ZodType<
  UploadFileResponseBody2,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function uploadFileResponseBody2FromJSON(
  jsonString: string,
): SafeParseResult<UploadFileResponseBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadFileResponseBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadFileResponseBody2' from JSON`,
  );
}

/** @internal */
export const UploadFileResponseBody1$inboundSchema: z.ZodType<
  UploadFileResponseBody1,
  z.ZodTypeDef,
  unknown
> = z.object({
  urls: z.array(types.string()),
});

export function uploadFileResponseBody1FromJSON(
  jsonString: string,
): SafeParseResult<UploadFileResponseBody1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadFileResponseBody1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadFileResponseBody1' from JSON`,
  );
}

/** @internal */
export const UploadFileResponseBody$inboundSchema: z.ZodType<
  UploadFileResponseBody,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  z.lazy(() => UploadFileResponseBody1$inboundSchema),
  z.lazy(() => UploadFileResponseBody2$inboundSchema),
]);

export function uploadFileResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UploadFileResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadFileResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadFileResponseBody' from JSON`,
  );
}
