/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UploadProjectAvatarAbuse,
  UploadProjectAvatarAbuse$inboundSchema,
  UploadProjectAvatarAlias,
  UploadProjectAvatarAlias$inboundSchema,
  UploadProjectAvatarAnalytics,
  UploadProjectAvatarAnalytics$inboundSchema,
  UploadProjectAvatarBlobs,
  UploadProjectAvatarBlobs$inboundSchema,
  UploadProjectAvatarConnectConfigurations,
  UploadProjectAvatarConnectConfigurations$inboundSchema,
  UploadProjectAvatarCreator,
  UploadProjectAvatarCreator$inboundSchema,
  UploadProjectAvatarCrons,
  UploadProjectAvatarCrons$inboundSchema,
  UploadProjectAvatarCustomEnvironments,
  UploadProjectAvatarCustomEnvironments$inboundSchema,
  UploadProjectAvatarDataCache,
  UploadProjectAvatarDataCache$inboundSchema,
  UploadProjectAvatarDefaultResourceConfig,
  UploadProjectAvatarDefaultResourceConfig$inboundSchema,
  UploadProjectAvatarDeploymentExpiration,
  UploadProjectAvatarDeploymentExpiration$inboundSchema,
  UploadProjectAvatarDeploymentPolicy,
  UploadProjectAvatarDeploymentPolicy$inboundSchema,
  UploadProjectAvatarDismissedToasts,
  UploadProjectAvatarDismissedToasts$inboundSchema,
  UploadProjectAvatarEnv,
  UploadProjectAvatarEnv$inboundSchema,
  UploadProjectAvatarExpiration,
  UploadProjectAvatarExpiration$inboundSchema,
  UploadProjectAvatarFeatures,
  UploadProjectAvatarFeatures$inboundSchema,
  UploadProjectAvatarFramework,
  UploadProjectAvatarFramework$inboundSchema,
  UploadProjectAvatarGitComments,
  UploadProjectAvatarGitComments$inboundSchema,
  UploadProjectAvatarGitProviderOptions,
  UploadProjectAvatarGitProviderOptions$inboundSchema,
} from "./uploadprojectavatargitprovideroptions.js";
import {
  UploadProjectAvatarInternalRoutes,
  UploadProjectAvatarInternalRoutes$inboundSchema,
  UploadProjectAvatarIpBuckets,
  UploadProjectAvatarIpBuckets$inboundSchema,
  UploadProjectAvatarJobs,
  UploadProjectAvatarJobs$inboundSchema,
  UploadProjectAvatarLastAliasRequest,
  UploadProjectAvatarLastAliasRequest$inboundSchema,
  UploadProjectAvatarLastRollbackTarget,
  UploadProjectAvatarLastRollbackTarget$inboundSchema,
  UploadProjectAvatarLatestDeployments,
  UploadProjectAvatarLatestDeployments$inboundSchema,
  UploadProjectAvatarLink,
  UploadProjectAvatarLink$inboundSchema,
  UploadProjectAvatarMicrofrontends,
  UploadProjectAvatarMicrofrontends$inboundSchema,
  UploadProjectAvatarNodeVersion,
  UploadProjectAvatarNodeVersion$inboundSchema,
  UploadProjectAvatarOidcProviders,
  UploadProjectAvatarOidcProviders$inboundSchema,
  UploadProjectAvatarOidcTokenConfig,
  UploadProjectAvatarOidcTokenConfig$inboundSchema,
  UploadProjectAvatarOptionsAllowlist,
  UploadProjectAvatarOptionsAllowlist$inboundSchema,
  UploadProjectAvatarPassport,
  UploadProjectAvatarPassport$inboundSchema,
  UploadProjectAvatarPasswordProtection,
  UploadProjectAvatarPasswordProtection$inboundSchema,
  UploadProjectAvatarPermissions,
  UploadProjectAvatarPermissions$inboundSchema,
  UploadProjectAvatarProtectionBypass,
  UploadProjectAvatarProtectionBypass$inboundSchema,
  UploadProjectAvatarProtectionConfig,
  UploadProjectAvatarProtectionConfig$inboundSchema,
  UploadProjectAvatarResourceConfig,
  UploadProjectAvatarResourceConfig$inboundSchema,
  UploadProjectAvatarRollbackDescription,
  UploadProjectAvatarRollbackDescription$inboundSchema,
  UploadProjectAvatarRollingRelease,
  UploadProjectAvatarRollingRelease$inboundSchema,
  UploadProjectAvatarSandbox,
  UploadProjectAvatarSandbox$inboundSchema,
  UploadProjectAvatarSecurity,
  UploadProjectAvatarSecurity$inboundSchema,
  UploadProjectAvatarServices,
  UploadProjectAvatarServices$inboundSchema,
  UploadProjectAvatarSpeedInsights,
  UploadProjectAvatarSpeedInsights$inboundSchema,
  UploadProjectAvatarSsoProtection,
  UploadProjectAvatarSsoProtection$inboundSchema,
  UploadProjectAvatarStaticIps,
  UploadProjectAvatarStaticIps$inboundSchema,
  UploadProjectAvatarTargets,
  UploadProjectAvatarTargets$inboundSchema,
  UploadProjectAvatarTier,
  UploadProjectAvatarTier$inboundSchema,
  UploadProjectAvatarTracing,
  UploadProjectAvatarTracing$inboundSchema,
  UploadProjectAvatarTrustedIps,
  UploadProjectAvatarTrustedIps$inboundSchema,
} from "./uploadprojectavataroidcproviders.js";

export const UploadProjectAvatarFromProjectsPreset = {
  AllCustom: "all-custom",
} as const;
export type UploadProjectAvatarFromProjectsPreset = ClosedEnum<
  typeof UploadProjectAvatarFromProjectsPreset
>;

/**
 * The source envs on the trusted project that are allowed to access `to`.
 */
export type UploadProjectAvatarFrom2 = {
  preset: UploadProjectAvatarFromProjectsPreset;
  /**
   * System environment slugs (`production`, `preview`) and/or custom environment slugs defined on the referenced project.
   */
  slugs?: Array<string> | undefined;
};

export const UploadProjectAvatarFromPreset = {
  AllCustom: "all-custom",
} as const;
export type UploadProjectAvatarFromPreset = ClosedEnum<
  typeof UploadProjectAvatarFromPreset
>;

/**
 * The source envs on the trusted project that are allowed to access `to`.
 */
export type UploadProjectAvatarFrom1 = {
  preset?: UploadProjectAvatarFromPreset | undefined;
  /**
   * System environment slugs (`production`, `preview`) and/or custom environment slugs defined on the referenced project.
   */
  slugs: Array<string>;
};

export type UploadProjectAvatarFrom =
  | UploadProjectAvatarFrom1
  | UploadProjectAvatarFrom2;

export const UploadProjectAvatarToProjectsResponse200Preset = {
  AllCustom: "all-custom",
} as const;
export type UploadProjectAvatarToProjectsResponse200Preset = ClosedEnum<
  typeof UploadProjectAvatarToProjectsResponse200Preset
>;

/**
 * The target envs on the current project that may be accessed.
 */
export type UploadProjectAvatarToProjects2 = {
  preset: UploadProjectAvatarToProjectsResponse200Preset;
  /**
   * System environment slugs (`production`, `preview`) and/or custom environment slugs defined on the referenced project.
   */
  slugs?: Array<string> | undefined;
};

export const UploadProjectAvatarToProjectsResponsePreset = {
  AllCustom: "all-custom",
} as const;
export type UploadProjectAvatarToProjectsResponsePreset = ClosedEnum<
  typeof UploadProjectAvatarToProjectsResponsePreset
>;

/**
 * The target envs on the current project that may be accessed.
 */
export type UploadProjectAvatarToProjects1 = {
  preset?: UploadProjectAvatarToProjectsResponsePreset | undefined;
  /**
   * System environment slugs (`production`, `preview`) and/or custom environment slugs defined on the referenced project.
   */
  slugs: Array<string>;
};

export type UploadProjectAvatarProjectsTo =
  | UploadProjectAvatarToProjects1
  | UploadProjectAvatarToProjects2;

/**
 * Optional overrides for the default same-env-by-slug matching. Provide explicit rules to allow cross-env access or presets.
 */
export type UploadProjectAvatarCustomAllow = {
  from: UploadProjectAvatarFrom1 | UploadProjectAvatarFrom2;
  to: UploadProjectAvatarToProjects1 | UploadProjectAvatarToProjects2;
};

export type UploadProjectAvatarProjects = {
  /**
   * Optional overrides for the default same-env-by-slug matching. Provide explicit rules to allow cross-env access or presets.
   */
  customAllow?: Array<UploadProjectAvatarCustomAllow> | undefined;
  label?: string | undefined;
};

export type UploadProjectAvatarTrustedSources = {
  /**
   * Allow same-team Vercel CI access to preview deployments built from the CI run's repository, using the deployment source rather than the current project repository link. Defaults to enabled when not stored; omitted or null Trusted Sources updates preserve the stored value.
   */
  enableVercelCiSameRepository?: boolean | undefined;
  oidcProviders?:
    | { [k: string]: Array<UploadProjectAvatarOidcProviders> }
    | undefined;
  projects?: { [k: string]: UploadProjectAvatarProjects } | undefined;
};

/**
 * Billing mode. Always 'flat' for flat-rate projects.
 */
export const UploadProjectAvatarKind = {
  Flat: "flat",
} as const;
/**
 * Billing mode. Always 'flat' for flat-rate projects.
 */
export type UploadProjectAvatarKind = ClosedEnum<
  typeof UploadProjectAvatarKind
>;

export type UploadProjectAvatarUsageStatus = {
  /**
   * Timestamp until which throttling is bypassed (project pays list rates for overage).
   */
  bypassThrottleUntil?: number | undefined;
  /**
   * Timestamp until which the project has exceeded its CDN allowance.
   */
  exceededAllowanceUntil?: number | undefined;
  /**
   * Billing mode. Always 'flat' for flat-rate projects.
   */
  kind: UploadProjectAvatarKind;
  /**
   * Synced from `team.billing.usageStatus.throttled`. When `true`, the team has throttled all of its projects regardless of `throttled`. The effective throttle the CDN enforces is `throttled || teamThrottled`.
   */
  teamThrottled?: boolean | undefined;
  /**
   * Per-project throttle, set explicitly for this project (e.g. via the per-project Flat Rate CDN endpoint).
   */
  throttled?: boolean | undefined;
};

export type UploadProjectAvatarWebAnalytics = {
  canceledAt?: number | undefined;
  disabledAt?: number | undefined;
  enabledAt?: number | undefined;
  hasData?: true | undefined;
  id: string;
};

export type UploadProjectAvatarResponseBody = {
  abuse?: UploadProjectAvatarAbuse | undefined;
  accountId: string;
  alias: Array<UploadProjectAvatarAlias>;
  analytics?: UploadProjectAvatarAnalytics | undefined;
  appliedCve55182Migration?: boolean | undefined;
  autoAssignCustomDomains?: boolean | undefined;
  autoAssignCustomDomainsUpdatedBy?: string | undefined;
  autoExposeSystemEnvs?: boolean | undefined;
  avatar?: string | null | undefined;
  blobs?: UploadProjectAvatarBlobs | undefined;
  buildCommand?: string | null | undefined;
  commandForIgnoringBuildStep?: string | null | undefined;
  concurrencyBucketName?: string | undefined;
  connectBuildsEnabled?: boolean | undefined;
  connectConfigurationId?: string | null | undefined;
  connectConfigurations?:
    | Array<UploadProjectAvatarConnectConfigurations>
    | null
    | undefined;
  createdAt?: number | undefined;
  creator?: UploadProjectAvatarCreator | undefined;
  crons?: UploadProjectAvatarCrons | undefined;
  customEnvironments?: Array<UploadProjectAvatarCustomEnvironments> | undefined;
  customerSupportCodeVisibility?: boolean | undefined;
  dataCache?: UploadProjectAvatarDataCache | undefined;
  defaultResourceConfig: UploadProjectAvatarDefaultResourceConfig;
  /**
   * Retention policies for deployments. These are enforced at the project level, but we also maintain an instance of this at the team level as a default policy that gets applied to new projects.
   */
  deploymentExpiration: UploadProjectAvatarDeploymentExpiration;
  /**
   * Project shape. `null` on a rule list clears the project's override for that rule type (fall back to team for every env); omitting is equivalent. Setting `deploymentPolicy` itself to `null` clears every override at once. Kept structurally distinct from {@link TeamDeploymentPolicy} so the two storage locations don't share a type by accident.
   */
  deploymentPolicy?: UploadProjectAvatarDeploymentPolicy | null | undefined;
  devCommand?: string | null | undefined;
  directoryListing: boolean;
  dismissedToasts?: Array<UploadProjectAvatarDismissedToasts> | undefined;
  enableAffectedProjectsDeployments?: boolean | undefined;
  enableExternalRewriteCaching?: boolean | undefined;
  enablePreviewFeedback?: boolean | null | undefined;
  enableProductionFeedback?: boolean | null | undefined;
  env?: Array<UploadProjectAvatarEnv> | undefined;
  expiration?: UploadProjectAvatarExpiration | undefined;
  features?: UploadProjectAvatarFeatures | undefined;
  framework?: UploadProjectAvatarFramework | null | undefined;
  gitComments?: UploadProjectAvatarGitComments | undefined;
  gitForkProtection?: boolean | undefined;
  gitLFS?: boolean | undefined;
  gitProviderOptions?: UploadProjectAvatarGitProviderOptions | undefined;
  hasActiveBranches?: boolean | undefined;
  hasDeployments?: boolean | undefined;
  id: string;
  installCommand?: string | null | undefined;
  internalRoutes?: Array<UploadProjectAvatarInternalRoutes> | undefined;
  ipBuckets?: Array<UploadProjectAvatarIpBuckets> | undefined;
  jobs?: UploadProjectAvatarJobs | undefined;
  lastAliasRequest?: UploadProjectAvatarLastAliasRequest | null | undefined;
  lastRollbackTarget?: UploadProjectAvatarLastRollbackTarget | null | undefined;
  latestDeployments?: Array<UploadProjectAvatarLatestDeployments> | undefined;
  link?: UploadProjectAvatarLink | undefined;
  live?: boolean | undefined;
  microfrontends?: UploadProjectAvatarMicrofrontends | undefined;
  name: string;
  nodeVersion: UploadProjectAvatarNodeVersion;
  oidcTokenConfig?: UploadProjectAvatarOidcTokenConfig | undefined;
  optionsAllowlist?: UploadProjectAvatarOptionsAllowlist | null | undefined;
  outputDirectory?: string | null | undefined;
  passiveConnectConfigurationId?: string | null | undefined;
  passport?: UploadProjectAvatarPassport | null | undefined;
  passwordProtection?: UploadProjectAvatarPasswordProtection | null | undefined;
  paused?: boolean | undefined;
  /**
   * Requested and authorized operations when `checkPermissions` is used. Legacy `includePermissions` responses contain a broader, non-authoritative permission summary.
   */
  permissions?: UploadProjectAvatarPermissions | undefined;
  productionDeploymentsFastLane?: boolean | undefined;
  protectedSourcemaps?: boolean | undefined;
  protectionBypass?:
    | { [k: string]: UploadProjectAvatarProtectionBypass }
    | undefined;
  protectionConfig?: UploadProjectAvatarProtectionConfig | undefined;
  resourceConfig: UploadProjectAvatarResourceConfig;
  /**
   * Description of why a project was rolled back, and by whom. Note that lastAliasRequest contains the from/to details of the rollback.
   */
  rollbackDescription?: UploadProjectAvatarRollbackDescription | undefined;
  /**
   * Project-level rolling release configuration that defines how deployments should be gradually rolled out
   */
  rollingRelease?: UploadProjectAvatarRollingRelease | null | undefined;
  rootDirectory?: string | null | undefined;
  sandbox?: UploadProjectAvatarSandbox | undefined;
  security?: UploadProjectAvatarSecurity | undefined;
  serverlessFunctionZeroConfigFailover?: boolean | undefined;
  services?: Array<UploadProjectAvatarServices> | undefined;
  skewProtectionAllowedDomains?: Array<string> | undefined;
  skewProtectionBoundaryAt?: number | undefined;
  skewProtectionMaxAge?: number | undefined;
  skipGitConnectDuringLink?: boolean | undefined;
  sourceFilesOutsideRootDirectory?: boolean | undefined;
  speedInsights?: UploadProjectAvatarSpeedInsights | undefined;
  ssoProtection?: UploadProjectAvatarSsoProtection | null | undefined;
  staticIps?: UploadProjectAvatarStaticIps | undefined;
  targets?: { [k: string]: UploadProjectAvatarTargets | null } | undefined;
  tier?: UploadProjectAvatarTier | undefined;
  tracing?: UploadProjectAvatarTracing | undefined;
  transferCompletedAt?: number | undefined;
  transferredFromAccountId?: string | undefined;
  transferStartedAt?: number | undefined;
  transferToAccountId?: string | undefined;
  trustedIps?: UploadProjectAvatarTrustedIps | null | undefined;
  trustedSources?: UploadProjectAvatarTrustedSources | null | undefined;
  updatedAt?: number | undefined;
  usageStatus?: UploadProjectAvatarUsageStatus | undefined;
  v0?: boolean | undefined;
  v0Created?: boolean | undefined;
  webAnalytics?: UploadProjectAvatarWebAnalytics | undefined;
};

/** @internal */
export const UploadProjectAvatarFromProjectsPreset$inboundSchema:
  z.ZodNativeEnum<typeof UploadProjectAvatarFromProjectsPreset> = z.nativeEnum(
    UploadProjectAvatarFromProjectsPreset,
  );

/** @internal */
export const UploadProjectAvatarFrom2$inboundSchema: z.ZodType<
  UploadProjectAvatarFrom2,
  z.ZodTypeDef,
  unknown
> = z.object({
  preset: UploadProjectAvatarFromProjectsPreset$inboundSchema,
  slugs: types.optional(z.array(types.string())),
});

export function uploadProjectAvatarFrom2FromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarFrom2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarFrom2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarFrom2' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarFromPreset$inboundSchema: z.ZodNativeEnum<
  typeof UploadProjectAvatarFromPreset
> = z.nativeEnum(UploadProjectAvatarFromPreset);

/** @internal */
export const UploadProjectAvatarFrom1$inboundSchema: z.ZodType<
  UploadProjectAvatarFrom1,
  z.ZodTypeDef,
  unknown
> = z.object({
  preset: types.optional(UploadProjectAvatarFromPreset$inboundSchema),
  slugs: z.array(types.string()),
});

export function uploadProjectAvatarFrom1FromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarFrom1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarFrom1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarFrom1' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarFrom$inboundSchema: z.ZodType<
  UploadProjectAvatarFrom,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  z.lazy(() => UploadProjectAvatarFrom1$inboundSchema),
  z.lazy(() => UploadProjectAvatarFrom2$inboundSchema),
]);

export function uploadProjectAvatarFromFromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarFrom' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarToProjectsResponse200Preset$inboundSchema:
  z.ZodNativeEnum<typeof UploadProjectAvatarToProjectsResponse200Preset> = z
    .nativeEnum(UploadProjectAvatarToProjectsResponse200Preset);

/** @internal */
export const UploadProjectAvatarToProjects2$inboundSchema: z.ZodType<
  UploadProjectAvatarToProjects2,
  z.ZodTypeDef,
  unknown
> = z.object({
  preset: UploadProjectAvatarToProjectsResponse200Preset$inboundSchema,
  slugs: types.optional(z.array(types.string())),
});

export function uploadProjectAvatarToProjects2FromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarToProjects2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarToProjects2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarToProjects2' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarToProjectsResponsePreset$inboundSchema:
  z.ZodNativeEnum<typeof UploadProjectAvatarToProjectsResponsePreset> = z
    .nativeEnum(UploadProjectAvatarToProjectsResponsePreset);

/** @internal */
export const UploadProjectAvatarToProjects1$inboundSchema: z.ZodType<
  UploadProjectAvatarToProjects1,
  z.ZodTypeDef,
  unknown
> = z.object({
  preset: types.optional(
    UploadProjectAvatarToProjectsResponsePreset$inboundSchema,
  ),
  slugs: z.array(types.string()),
});

export function uploadProjectAvatarToProjects1FromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarToProjects1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarToProjects1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarToProjects1' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarProjectsTo$inboundSchema: z.ZodType<
  UploadProjectAvatarProjectsTo,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  z.lazy(() => UploadProjectAvatarToProjects1$inboundSchema),
  z.lazy(() => UploadProjectAvatarToProjects2$inboundSchema),
]);

export function uploadProjectAvatarProjectsToFromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarProjectsTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarProjectsTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarProjectsTo' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarCustomAllow$inboundSchema: z.ZodType<
  UploadProjectAvatarCustomAllow,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: smartUnion([
    z.lazy(() => UploadProjectAvatarFrom1$inboundSchema),
    z.lazy(() => UploadProjectAvatarFrom2$inboundSchema),
  ]),
  to: smartUnion([
    z.lazy(() => UploadProjectAvatarToProjects1$inboundSchema),
    z.lazy(() => UploadProjectAvatarToProjects2$inboundSchema),
  ]),
});

export function uploadProjectAvatarCustomAllowFromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarCustomAllow, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarCustomAllow$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarCustomAllow' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarProjects$inboundSchema: z.ZodType<
  UploadProjectAvatarProjects,
  z.ZodTypeDef,
  unknown
> = z.object({
  customAllow: types.optional(
    z.array(z.lazy(() => UploadProjectAvatarCustomAllow$inboundSchema)),
  ),
  label: types.optional(types.string()),
});

export function uploadProjectAvatarProjectsFromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarProjects, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarProjects$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarProjects' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarTrustedSources$inboundSchema: z.ZodType<
  UploadProjectAvatarTrustedSources,
  z.ZodTypeDef,
  unknown
> = z.object({
  enableVercelCiSameRepository: types.optional(types.boolean()),
  oidcProviders: types.optional(
    z.record(z.array(UploadProjectAvatarOidcProviders$inboundSchema)),
  ),
  projects: types.optional(
    z.record(z.lazy(() => UploadProjectAvatarProjects$inboundSchema)),
  ),
});

export function uploadProjectAvatarTrustedSourcesFromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarTrustedSources, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarTrustedSources$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarTrustedSources' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarKind$inboundSchema: z.ZodNativeEnum<
  typeof UploadProjectAvatarKind
> = z.nativeEnum(UploadProjectAvatarKind);

/** @internal */
export const UploadProjectAvatarUsageStatus$inboundSchema: z.ZodType<
  UploadProjectAvatarUsageStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  bypassThrottleUntil: types.optional(types.number()),
  exceededAllowanceUntil: types.optional(types.number()),
  kind: UploadProjectAvatarKind$inboundSchema,
  teamThrottled: types.optional(types.boolean()),
  throttled: types.optional(types.boolean()),
});

export function uploadProjectAvatarUsageStatusFromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarUsageStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarUsageStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarUsageStatus' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarWebAnalytics$inboundSchema: z.ZodType<
  UploadProjectAvatarWebAnalytics,
  z.ZodTypeDef,
  unknown
> = z.object({
  canceledAt: types.optional(types.number()),
  disabledAt: types.optional(types.number()),
  enabledAt: types.optional(types.number()),
  hasData: types.optional(types.literal(true)),
  id: types.string(),
});

export function uploadProjectAvatarWebAnalyticsFromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarWebAnalytics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarWebAnalytics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarWebAnalytics' from JSON`,
  );
}

/** @internal */
export const UploadProjectAvatarResponseBody$inboundSchema: z.ZodType<
  UploadProjectAvatarResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  abuse: types.optional(UploadProjectAvatarAbuse$inboundSchema),
  accountId: types.string(),
  alias: z.array(UploadProjectAvatarAlias$inboundSchema),
  analytics: types.optional(UploadProjectAvatarAnalytics$inboundSchema),
  appliedCve55182Migration: types.optional(types.boolean()),
  autoAssignCustomDomains: types.optional(types.boolean()),
  autoAssignCustomDomainsUpdatedBy: types.optional(types.string()),
  autoExposeSystemEnvs: types.optional(types.boolean()),
  avatar: z.nullable(types.string()).optional(),
  blobs: types.optional(UploadProjectAvatarBlobs$inboundSchema),
  buildCommand: z.nullable(types.string()).optional(),
  commandForIgnoringBuildStep: z.nullable(types.string()).optional(),
  concurrencyBucketName: types.optional(types.string()),
  connectBuildsEnabled: types.optional(types.boolean()),
  connectConfigurationId: z.nullable(types.string()).optional(),
  connectConfigurations: z.nullable(
    z.array(UploadProjectAvatarConnectConfigurations$inboundSchema),
  ).optional(),
  createdAt: types.optional(types.number()),
  creator: types.optional(UploadProjectAvatarCreator$inboundSchema),
  crons: types.optional(UploadProjectAvatarCrons$inboundSchema),
  customEnvironments: types.optional(
    z.array(UploadProjectAvatarCustomEnvironments$inboundSchema),
  ),
  customerSupportCodeVisibility: types.optional(types.boolean()),
  dataCache: types.optional(UploadProjectAvatarDataCache$inboundSchema),
  defaultResourceConfig: UploadProjectAvatarDefaultResourceConfig$inboundSchema,
  deploymentExpiration: UploadProjectAvatarDeploymentExpiration$inboundSchema,
  deploymentPolicy: z.nullable(
    UploadProjectAvatarDeploymentPolicy$inboundSchema,
  ).optional(),
  devCommand: z.nullable(types.string()).optional(),
  directoryListing: types.boolean(),
  dismissedToasts: types.optional(
    z.array(UploadProjectAvatarDismissedToasts$inboundSchema),
  ),
  enableAffectedProjectsDeployments: types.optional(types.boolean()),
  enableExternalRewriteCaching: types.optional(types.boolean()),
  enablePreviewFeedback: z.nullable(types.boolean()).optional(),
  enableProductionFeedback: z.nullable(types.boolean()).optional(),
  env: types.optional(z.array(UploadProjectAvatarEnv$inboundSchema)),
  expiration: types.optional(UploadProjectAvatarExpiration$inboundSchema),
  features: types.optional(UploadProjectAvatarFeatures$inboundSchema),
  framework: z.nullable(UploadProjectAvatarFramework$inboundSchema).optional(),
  gitComments: types.optional(UploadProjectAvatarGitComments$inboundSchema),
  gitForkProtection: types.optional(types.boolean()),
  gitLFS: types.optional(types.boolean()),
  gitProviderOptions: types.optional(
    UploadProjectAvatarGitProviderOptions$inboundSchema,
  ),
  hasActiveBranches: types.optional(types.boolean()),
  hasDeployments: types.optional(types.boolean()),
  id: types.string(),
  installCommand: z.nullable(types.string()).optional(),
  internalRoutes: types.optional(
    z.array(UploadProjectAvatarInternalRoutes$inboundSchema),
  ),
  ipBuckets: types.optional(
    z.array(UploadProjectAvatarIpBuckets$inboundSchema),
  ),
  jobs: types.optional(UploadProjectAvatarJobs$inboundSchema),
  lastAliasRequest: z.nullable(
    UploadProjectAvatarLastAliasRequest$inboundSchema,
  ).optional(),
  lastRollbackTarget: z.nullable(
    UploadProjectAvatarLastRollbackTarget$inboundSchema,
  ).optional(),
  latestDeployments: types.optional(
    z.array(UploadProjectAvatarLatestDeployments$inboundSchema),
  ),
  link: types.optional(UploadProjectAvatarLink$inboundSchema),
  live: types.optional(types.boolean()),
  microfrontends: types.optional(
    UploadProjectAvatarMicrofrontends$inboundSchema,
  ),
  name: types.string(),
  nodeVersion: UploadProjectAvatarNodeVersion$inboundSchema,
  oidcTokenConfig: types.optional(
    UploadProjectAvatarOidcTokenConfig$inboundSchema,
  ),
  optionsAllowlist: z.nullable(
    UploadProjectAvatarOptionsAllowlist$inboundSchema,
  ).optional(),
  outputDirectory: z.nullable(types.string()).optional(),
  passiveConnectConfigurationId: z.nullable(types.string()).optional(),
  passport: z.nullable(UploadProjectAvatarPassport$inboundSchema).optional(),
  passwordProtection: z.nullable(
    UploadProjectAvatarPasswordProtection$inboundSchema,
  ).optional(),
  paused: types.optional(types.boolean()),
  permissions: types.optional(UploadProjectAvatarPermissions$inboundSchema),
  productionDeploymentsFastLane: types.optional(types.boolean()),
  protectedSourcemaps: types.optional(types.boolean()),
  protectionBypass: types.optional(
    z.record(UploadProjectAvatarProtectionBypass$inboundSchema),
  ),
  protectionConfig: types.optional(
    UploadProjectAvatarProtectionConfig$inboundSchema,
  ),
  resourceConfig: UploadProjectAvatarResourceConfig$inboundSchema,
  rollbackDescription: types.optional(
    UploadProjectAvatarRollbackDescription$inboundSchema,
  ),
  rollingRelease: z.nullable(UploadProjectAvatarRollingRelease$inboundSchema)
    .optional(),
  rootDirectory: z.nullable(types.string()).optional(),
  sandbox: types.optional(UploadProjectAvatarSandbox$inboundSchema),
  security: types.optional(UploadProjectAvatarSecurity$inboundSchema),
  serverlessFunctionZeroConfigFailover: types.optional(types.boolean()),
  services: types.optional(z.array(UploadProjectAvatarServices$inboundSchema)),
  skewProtectionAllowedDomains: types.optional(z.array(types.string())),
  skewProtectionBoundaryAt: types.optional(types.number()),
  skewProtectionMaxAge: types.optional(types.number()),
  skipGitConnectDuringLink: types.optional(types.boolean()),
  sourceFilesOutsideRootDirectory: types.optional(types.boolean()),
  speedInsights: types.optional(UploadProjectAvatarSpeedInsights$inboundSchema),
  ssoProtection: z.nullable(UploadProjectAvatarSsoProtection$inboundSchema)
    .optional(),
  staticIps: types.optional(UploadProjectAvatarStaticIps$inboundSchema),
  targets: types.optional(
    z.record(types.nullable(UploadProjectAvatarTargets$inboundSchema)),
  ),
  tier: types.optional(UploadProjectAvatarTier$inboundSchema),
  tracing: types.optional(UploadProjectAvatarTracing$inboundSchema),
  transferCompletedAt: types.optional(types.number()),
  transferredFromAccountId: types.optional(types.string()),
  transferStartedAt: types.optional(types.number()),
  transferToAccountId: types.optional(types.string()),
  trustedIps: z.nullable(UploadProjectAvatarTrustedIps$inboundSchema)
    .optional(),
  trustedSources: z.nullable(
    z.lazy(() => UploadProjectAvatarTrustedSources$inboundSchema),
  ).optional(),
  updatedAt: types.optional(types.number()),
  usageStatus: types.optional(
    z.lazy(() => UploadProjectAvatarUsageStatus$inboundSchema),
  ),
  v0: types.optional(types.boolean()),
  v0Created: types.optional(types.boolean()),
  webAnalytics: types.optional(
    z.lazy(() => UploadProjectAvatarWebAnalytics$inboundSchema),
  ),
});

export function uploadProjectAvatarResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UploadProjectAvatarResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadProjectAvatarResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadProjectAvatarResponseBody' from JSON`,
  );
}
